### ISSUE TITLE
(#131) Missing decimal digits/partial amounts on the Receipts

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#100]
Found that the decimal digits/partial amounts on the Receipts:

See the item below: Rx 242, Rx 235 are showing up on the receipts as $5.00 and $3.00 while the original price is $5.15 and $3.33 respectively.  Verified that data is being sent correctly. 
Please refer the request object attached. (https://github.com/rxtrax/tracking/files/735543/request.txt)

** External ID: 8912248 **

![partial - decimal digits missing on the receipts](https://cloud.githubusercontent.com/assets/8714134/22375805/f404a91e-e481-11e6-83a2-7b9a248522f9.jpg)

![ipad receipt - markings](https://cloud.githubusercontent.com/assets/8714134/22376204/7245ea58-e483-11e6-888b-7fc8a2bea355.PNG)

![partial](https://cloud.githubusercontent.com/assets/8714134/22375722/9f6e89e2-e481-11e6-88a4-264b4b0ee0b3.png)

**Comment by jasonmadrid** [comment]
This has been fixed.
