### ISSUE TITLE
The amount collected at the time of delivery is not reflecting in the call back to EnterpriseRX

### ISSUE THREAD

**Issue by gopiraj24** [rxtrax/tracking#102]
The amount collected at the time of delivery is not reflecting in the call back to EnterpriseRX

The soap message send back should contained the paid amount at the time of delivery.

Please check this segment of the message being sent, the amount collected whould contain the value collected at the time of delviery.
` <ns1:RxSoldInfo AmountCollected="0" PatientPaySource="T" ReasonCode="S1" TaxCollected="0" TimeStamp="2017-01-29T21:06:06.000+00:00" UserID="3"/>`

**Comment by gopiraj24** [comment]
@jasonmadrid  I think we may need to revisit how this will work.

**Comment by jasonmadrid** [comment]
This has been implemented based on a design worked out with @gopiraj24.  Enterprise is sending the amount in the `delivery_prescription.total_price` field, and we are reporting it back as `AmountCollected`.
