### ISSUE TITLE
Call Back Functionality not working as expected in Enterprise Rx application

### ISSUE THREAD

**Issue by sindhujan-sid** [rxtrax/tracking#103]
**Summary :** Rx sold in RxTrax application not changing/reflecting to sold in Enterprise Rx application.

**NOTE: The Functionality was working as expected till 2.30 AM EST.**

**Request sent  :** 
{"external_id":"cps-ERX-NDCQ34-BUT-deliveries-10292023951&23213801","delivery_date":1485734400,"deliver_before":1485765180,"address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","collect_amount":70797.31,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":false,"cancelled_on":null,"recipient":{"external_id":"cps-ERX-NDCQ34-BUT-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"external_route_id":"5886fee495cd9","delivery_prescriptions":[{"external_id":"cps-ERX-NDCQ34-BUT-delivery_prescriptions-10163100578","quantity":"30.0","fill_number":0,"partial_fill_sequence":0,"prescription":{"external_id":"cps-ERX-NDCQ34-BUT-prescription-10163100578","rx_number":"004115","description":"HUMIRA 10MG/0.2ML PSKT","customer":{"external_id":"cps-ERX-NDCQ34-BUT-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"cps-ERX-NDCQ34-BUT-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":true},{"external_id":"cps-ERX-NDCQ34-BUT-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":true}],"is_archived":false}

**Ready Rx :** 
![004115 - ready](https://cloud.githubusercontent.com/assets/25191682/22424843/6abdc100-e71e-11e6-971d-a9ae7c56990f.PNG)

**Sold Rx :**
![004115 - sold](https://cloud.githubusercontent.com/assets/25191682/22424844/6c5d613c-e71e-11e6-8719-02712acabb80.PNG)

**Comment by sindhujan-sid** [comment]
@jasonmadrid  please look into the above issue.

**Comment by jasonmadrid** [comment]
I see several callback attempts with the following response given:

```
<?xml version="1.0" encoding="UTF-8"?>
<ns1:Envelope xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/">
	<ns1:Header>
		<ns2:MsgHeader DestinationID="F123MOB" MsgID="1485657740759" MsgName="GenericFailureRsp" SendCount="1" SourceID="TREX" TimeStamp="2017-01-30T13:24:33.155+00:00" Version="1.0" xmlns:ns2="http://www.techrx.com/trexone/1_0"/>
	</ns1:Header>
	<ns1:Body>
		<ns2:GenericFailureRsp Actor="Server" Code="19" Detail="Rx 004115 not found." ErrorMsg="Rx 004115 not found." Severity="W" xmlns:ns2="http://www.techrx.com/trexone/1_0"/>
	</ns1:Body>
</ns1:Envelope>
```

**Comment by jasonmadrid** [comment]
I believe we've resolved the issues related to these callback failures.
