### ISSUE TITLE
(#133) Handle declines/failures when doing card transaction Cancel (Refund/Void). 

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#104]
(#133) Handle declines/failures when doing card transaction Cancel (Refund/Void). 

Currently, the application says "Refunds Completed" even when something goes wrong making refunds.

Please see the screenshots.

**Issues**:
1. Any declines during void should be handled.
2. If failure happens during 'decline' the message should be appropriate
3. Moreover, if decline happens during void/refund, the amount needs to be collected should not be reset to 0 regardless. The impact of this issue, currently, we are seeing that the API returns all collected money. 

**Steps**:
1. I used three cards and completed the payments. 
2. Clicked cancel and it initiated refunds. However while completing transactions, the processor returned "1012; Decline" error (meaning the refunds did not went through).
3. In this case, the application is reporting that the Refunds were completed. It should report that there was a failure while Voiding one (or more) card transactions.. 

![image](https://cloud.githubusercontent.com/assets/8714134/22473978/f4003528-e7b0-11e6-8aa9-ae9d34d71f73.png)

![image](https://cloud.githubusercontent.com/assets/8714134/22474017/14a9f9da-e7b1-11e6-92b0-fb40debf2d4c.png)

**Comment by jjamminjim** [comment]
@brprashanth could you add some screenshots?

**Comment by jjamminjim** [comment]
When a void does not succeed the driver is instructed to inform the customer to contact the pharmacy. The transaction is not canceled, and will represent itself when re-entering the payment window.
