### ISSUE TITLE
(#134) Credit card reversals (Void/Refunds) are not happening

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#105]
#134 Credit card reversals (Void/Refunds) are not happening. 

1. Tried multi card and single card payment.
2. The device is receiving 1012 decline errors and completing the refunds. These "Decline" attempts are not even showing up on the merchant-ware portal.
3. On some odd occasion it is completing the refund, 

However,  none of these refund/void activity is showing up on the merchant-ware portal as refunded/void for confirmation.

We feel that the  merchant id, key and name may be not the one that was used to initiate the transaction originally. Please check.

Please see the screenshots.

**Comment by jjamminjim** [comment]
@brprashanth could you add some screenshots?

**Comment by brprashanth** [comment]
This is an Firstdata processor issue. Tracking with Firstdata. 
Closing this issue for now.
