### ISSUE TITLE
(#136) Error message 'Communication error' displayed when wireless payment device is busy

### ISSUE THREAD

**Issue by archanamckesson** [rxtrax/tracking#107]
Warning message could display 'Payment device is busy , please try again' instead of Communication error

1. Create a transaction with RX for any amount 
2. Mark that as delivery item
3. First transaction pay with Partial payment FSA card 
4. Amount $5 paid successfully and patient will be signing for credit card transaction
5. Summary of transaction with Paid, remaining and total amount will be displayed on the Payment device
6. Amount details with OK button displayed on ipad
7. When driver tries to process the remaining amount while customer is verifying summary of first card transaction on payment device msg "communication error" displayed

**Comment by archanamckesson** [comment]
![img_0005 3](https://cloud.githubusercontent.com/assets/25255271/22473541/3df1f504-e7a7-11e6-801e-af81b71cecfd.PNG)

**Comment by brprashanth** [comment]
This seem to be fixed now.
