### ISSUE TITLE
(#137) - Intermittent Json Errors on IPAD even when the Cayan did not timeout yet.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#108]
After making a partial payment I waited a minute and looked at the ipad and saw a Json error. Looked at Cayan device and it is still working - no timeout or anything. I will attach print screens.

This happens intermittently on the IPAD, when when you are working with the Wireless device at the normal user speed. 

Also there is a spelling mistake there.

![json error](https://cloud.githubusercontent.com/assets/8714134/22474708/0e00a55a-e7b3-11e6-9d3c-aa807ec9ed15.jpg)
![not timed out](https://cloud.githubusercontent.com/assets/8714134/22474707/0df99ba2-e7b3-11e6-8d21-e2787d7e1abb.jpg)

**Comment by jjamminjim** [comment]
@brprashanth I can not reproduce this error.  Can you or your team try to reproduce and then send me the delivery id of the transaction that fails with this son error. Thanks

**Comment by brprashanth** [comment]
@jim. We have talked about this earlier and when you were in Livonia as well. This happens when the wireless device is waiting for customer signature or PIN entry for example and when you have left the IPAD for more than 2-3 minutes. The IPAD times out earlier than the wireless device.
