### ISSUE TITLE
(#139) Invalid Transport Key Error on IPAD - IPAD lag time in synchronizing while sending Pharmacy Patch request

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#110]
We have found this IPAD Application lag time when it synchronizes the latest information from the RxTrax servers. 

**Observations** :  

2.  If the driver initiates the Collect Payment on Credit card before the IPAD is updated it leads to "Invalid Transport Key"

**Comment by jjamminjim** [comment]
@brprashanth Could you break this into three separate issues?  #2 is fixed

**Comment by brprashanth** [comment]
sure @jjamminjim
