### ISSUE TITLE
(#142) Seeing this "The remote server returned an error: (403) Forbidden" intermittently.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#114]
We are seeing this intermittent error while trying to Post a Delivery **"The remote server returned an error: (403) Forbidden".**

**Logs**:
[RequestJson _110190014.txt](https://github.com/rxtrax/tracking/files/751091/RequestJson._110190014.txt)
[POS.log.txt](https://github.com/rxtrax/tracking/files/751097/POS.log.txt)

Our offshore QA is experiencing this as well. This is happening newly and happens around 4 out 10 times.

INFO [02/03/2017 03:44:31 AM ] MPSRxTraxComms::RegisterDelivery: Request Data: 
{"external_id":"110190014","delivery_date":1486080000,"deliver_before":"06:00 PM","deliver_after":"03:00 PM","instructions":"","address1":"2345 MAIN STREET","city":"WARREN","state":"MI","postal_code":"48093","collect_amount":4.0,"collect_info":{"TransactionType":"SALE","Amount":4.0000,"ClerkId":"ADMIN","OrderNumber":"RB034408","Dba":"Test McKesson Pharmaserv","SoftwareName":"Pharmaserv Point of Sale","SoftwareVersion":"GR 7.6.0.0","AddressLine1":null,"Zip":null,"Cardholder":null,"LogoLocation":null,"RedirectLocation":null,"TransactionId":"110190014","ForceDuplicate":false,"CustomerCode":"20190","PoNumber":"RB034408","TaxAmount":0.0000,"HealthCareAmountDetails":null,"EnablePartialAuthorization":true},"photo_id_required":true,"signature_required":false,"recipient_photo_required":true,"payment_required":true,"external_recepient_id":null,"recipient":{"external_id":"20190","first_name":"Alexis","last_name":"Adamsville","home_phone":"333-5555555","mobile_phone":"","email":"","address1":"2345 MAIN STREET","address2":"SUITE 20190","city":"WARREN","state":"MI","postal_code":"48093","country":"","facility":false,"notes":null,"is_archived":false},"external_route_id":"58591a1c6e35b","delivery_prescriptions":[{"external_id":"DP_110190014_7","prescription":{"external_id":"P_110190014_7","rx_number":"DELIVERY","description":"7","is_misc":true,"customer":null},"customer":{"external_id":"20190","first_name":"Adamsville","last_name":"Alexis","home_phone":"333-5555555","mobile_phone":"","email":"","address1":"2345 MAIN STREET","address2":"SUITE 20190","city":"WARREN","state":"MI","postal_code":"48093","country":"","facility":false,"is_archived":false},"quantity":1,"unit_price":1.0,"total_price":1.0},{"external_id":"DP_110190014_3","prescription":{"external_id":"P_110190014_3","rx_number":"NONQHP","description":"3","is_misc":true,"customer":null},"customer":{"external_id":"20190","first_name":"Adamsville","last_name":"Alexis","home_phone":"333-5555555","mobile_phone":"","email":"","address1":"2345 MAIN STREET","address2":"SUITE 20190","city":"WARREN","state":"MI","postal_code":"48093","country":"","facility":false,"is_archived":false},"quantity":1,"unit_price":3.0,"total_price":3.0}],"acknowledgements":null,"is_archived":false}
INFO [02/03/2017 03:44:31 AM ] MPSWebRequestManager::ProcessWebRequest: Entering Method ** URL: https://api.sandbox.getrxtrax.com/v1/deliveries?api_key=hh09WTF1hT2YYYMRkRdmwSG6s4ojG4f1nK64dKSFYPSAg5Ql9w
INFO [02/03/2017 03:45:34 AM ] MPSWebRequestManager::SendRequest: Entering Method
ERROR [02/03/2017 03:45:34 AM ] MPSWebRequestManager::SendRequest : Exception occured:Status:: ProtocolError :: Message::**The remote server returned an error: (403) Forbidden.**

**Comment by jasonmadrid** [comment]
It looks like you're trying to POST or PATCH to a `v1` endpoint.

**Comment by brprashanth** [comment]
This seem to be fixed now.
