### ISSUE TITLE
(#148) Add the ability to set header and footer notes on the receipts.   

### ISSUE THREAD

**Issue by RobinGK** [rxtrax/tracking#120]
The API should provide ability for the application to send header and footer messages once maybe during initial pharmacy setup. This setup should display those messages on the header and footer respectively on the receipts.  These messages could be configured via the Patch Pharmacy request.
Example of a footer message: 
Thank you for shopping with us today
We appreciate your business 
Please check out our website at:
www.RobinsRX.com 

This will be printed at the above the message that indicates the Qualified Healthcare Products.

**Comment by jjamminjim** [comment]
Add via `receipt_header` and `receipt_footer` in `payment_config`.

**Comment by RobinGK** [comment]
Thanks Jim  on all three of my questions.  I will send to Prashanth and we can try it..

Thanks,
Robin

**Comment by brprashanth** [comment]
Hi @jjamminjim, @jasonmadrid 
As suggested by you, we are sending the Header and Footer messages in the payment config.
The only thing that is pending now is the IPAD application to pick this up while printing receipts.  Thanks.
