### ISSUE TITLE
(#150) Invalid Transport Key Error on IPAD - Delay in updating patch pharmacy info

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#121]
When the Patch request for Pharmacy is sent, it takes minimum around 3-5 minutes, sometimes more - even 10-20 minutes for the IPAD to sync with the updated pharmacy (cayan merchant information - merchant id, merchant key, name).

This causes invalid Transport Key Error on IPAD.

#139.1

**Comment by brprashanth** [comment]
#139.1

**Comment by jjamminjim** [comment]
Same as 149 (github #122)
