### ISSUE TITLE
(#152) The QHP flag on the Receipt is displayed only for the Rx(s), it does not indicate for regular QHP items.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#125]
(#152) The QHP flag on the Receipt is displayed only for the Rx(s). There are few items such as Blood Pressure Monitors which are not Rx(s) but are QHP eligible. Currently can only differentiate between Rx and a Non-Rx.

This issue is happening because, the current API, 
1.  An item can be differentiated only as Rx or a Misc item.
2.  The API should provide the ability to distinguish a QHP item.
3.  The receipt should then indicate the QHP flag for both Rx(s) and QHP items(s).

**Comment by RyanNerd** [comment]
@jasonmadrid Will this require an additional field? Right now `IsMisc` typically indicates durable medial equipment or OTC drug. I'm assuming that QHP means Qualified Health Plan which would fall under the `isMisc=true` flag?

**Comment by brprashanth** [comment]
@RyanNerd . (QHP means Qualified health product)
Iterating again:
we need a way separate out Rx (by default QHP), QHP (Blood pressure monitor, OTC for example), and Non QHP (milk, chocolate, shampoo example)

Also hope you understand the use of Misc flags on the IPAD. 
We want a Tilde flag that to appear in front of Rx and a QHP
We dont want a Tilde flag to appear in front of Non-QHP.

**Comment by brprashanth** [comment]
Also, please understand there is another limitation on the IPAD. 
There are SKU and Description field and how it is currently handled for Misc and Non-Misc. Jim knows about this.
To handle all these problems, we need a clear way of identifying Rx, Qhp, Non-Qhp.

**Comment by jjamminjim** [comment]
The nonprescription bhp item is now flagged via the `is_qhp` field in Prescription record.

**Comment by brprashanth** [comment]
Could you please update the documentation please? We are not getting where to send the is_qhp flag.
