### ISSUE TITLE
(#153) Address Related issues on the API

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#126]
Currently there are following issue with the address fields:

Issues on the API:

1. Address line 2 missing on Delivery Address (The Override address field do not have address line 2)
2. There is no address line 3 in the API for sending any address - Recipient Address or Pos Delivery address 

![address issue](https://cloud.githubusercontent.com/assets/8714134/22700714/ecec637a-ed31-11e6-9602-b6a246a0249b.png)
[address line 1 and 2.txt](https://github.com/rxtrax/tracking/files/758347/address.line.1.and.2.txt)
[address line 1 only.txt](https://github.com/rxtrax/tracking/files/758348/address.line.1.only.txt)

**For Recipient address:**
Note the address 1, and address 2.
![image](https://cloud.githubusercontent.com/assets/8714134/22700673/d5c9fe46-ed31-11e6-8734-a6c508e90d97.png)

 **POS Delivery Address:**
Note the address 1,  missing address 2.
![image](https://cloud.githubusercontent.com/assets/8714134/22700694/e3245d02-ed31-11e6-8e72-372892cee266.png)

**Comment by RyanNerd** [comment]
This appears to be misunderstanding from incomplete documentation for the API. The API docs at http://docs.rxtrax.apiary.io/#reference/deliveries/delivery/patch-delivery need to be updated to include the `address` field. The `address` field is where the street address would be saved as the temporary address for a delivery and `address1` would contain things such as apartment and and suite #.

The Customer has `address1` and `address2` fields. Delivery has `address` and `address1` fields (which is admittedly confusing).

**Comment by brprashanth** [comment]
@RyanNerd  we dont want to over this again. Please go through the details given carefully.
We are not talking about the customer address that is under delivery prescription.
We are talking about the "override" delivery address.
Please see the documentation (the snapshot from the Rx Trax API doc). The address 2 is missing.
Jason also confirmed the address2 was missing in the database.

**Comment by jjamminjim** [comment]
Fixed on iPad : Address Lines 1 2 and 3 are now supported and properly displayed on the iPad.
@jasonmadrid will finish adding the missing address lines to the database and api.

**Comment by brprashanth** [comment]
@jjamminjim, thanks for the changes. The address line 3 is not displaying on the IPAD yet.
The address line 2 is not displaying on the Delivery Address field.

**Comment by jasonmadrid** [comment]
Everywhere there was an `address1` available in the API, there is now an `address2` and `address3`.
