### ISSUE TITLE
(#154) Address Issue on IPAD - City and Zip goes missing if you have included the Address Line 2

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#127]
On the Recipient When the patient has address line 1 and line 2  provided in Psv, then the recipient address(customer info) on the IPAD displays - address line 1, address line 2 and the phone number.

If you send address 1 and 2 on recipient field, the IPAD skips the city and zip code.

[address line 1 and 2.txt](https://github.com/rxtrax/tracking/files/758341/address.line.1.and.2.txt)
[address line 1 only.txt](https://github.com/rxtrax/tracking/files/758342/address.line.1.only.txt)

![address issue 2](https://cloud.githubusercontent.com/assets/8714134/22700544/79bb0a6e-ed31-11e6-87ae-12e080a82911.png)
![address issue](https://cloud.githubusercontent.com/assets/8714134/22700550/7d26440c-ed31-11e6-875e-95fb166aa9e6.png)

**Comment by jjamminjim** [comment]
Address Lines 1 2 and 3 are now supported and properly displayed on the iPad.

**Comment by brprashanth** [comment]
Reopening the issue with the below comments
1.	Address Line 2 is not appearing yet on the Delivery Address:
2.	As the per the comments on the Github, we tried Address Line 3, it is not displaying anywhere (Address line 3 is of very least priority at the moment. For us, issue #1 is more important)

![image](https://cloud.githubusercontent.com/assets/8714134/23807659/da8ac388-059c-11e7-9cc1-dcec873f81db.png)
![image](https://cloud.githubusercontent.com/assets/8714134/23807662/dbeb66ba-059c-11e7-8735-3d3695da752f.png)

**Comment by jasonmadrid** [comment]
Yes, waiting on #126

**Comment by jasonmadrid** [comment]
Everywhere there was an `address1` available in the API, there is now an `address2` and `address3`.
