### ISSUE TITLE
(#155) IPAD Stuck on Staging Transaction Message while making Credit card payments

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#128]
The application displays reader connected message. 
1. However, upon click of "Pay Now" it does not initiate anything on the Payment Device. However, after 5 minutes the IPAD received the message "multiple transactions created".
2. Now even though wireless device is showing the initiation of the payment, the IPAD has basically lost the connection. See screenshots.

Also, see the video attachment.  
[IMG_5469.zip](https://github.com/rxtrax/tracking/files/758598/IMG_5469.zip)

![img_5467](https://cloud.githubusercontent.com/assets/8714134/22705052/5ea3f312-ed40-11e6-9720-b6e60bf0d65c.JPG)
![img_5471](https://cloud.githubusercontent.com/assets/8714134/22705053/5ec1f704-ed40-11e6-9f49-c8c26f1b05bd.JPG)

**Finally Received this error after few minutes (2-3 minutes may be)**

![img_5473](https://cloud.githubusercontent.com/assets/8714134/22705056/62d73282-ed40-11e6-84ae-45c599ca6815.PNG)

![img_5472](https://cloud.githubusercontent.com/assets/8714134/22705063/6dbd3dc2-ed40-11e6-94b9-f6e00c48971a.JPG)

**Comment by jjamminjim** [comment]
@brprashanth I can not reproduce this error either.  Can you or your team try to reproduce and then send me the delivery id of the transaction that fails with this error. Thanks

**Comment by brprashanth** [comment]
It was hard to recreate last time too Jim. We will keep an eye on this.
But one thing, this happened when the IPAD was stuck with the message "Staging Transaction".
