### ISSUE TITLE
7.6.0- (#159) Receipts are displayed in random order in the Priority tab in RxTrax.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#132]
When we add receipts to delivery queue, it gets displayed in random order in the priority queue of RxTrax app.

Expected:The last added receipt should get displayed at the bottom according to priority.

![priority rxtrax](https://cloud.githubusercontent.com/assets/8714134/22708457/a97f90ec-ed4c-11e6-9a00-a97edcdf5df8.jpg)
![priority order](https://cloud.githubusercontent.com/assets/8714134/22708456/a97de95e-ed4c-11e6-8645-5bbb4d49eb11.JPG)

**Comment by jjamminjim** [comment]
@brprashanth Can you give me the log-in for this pharmacy.

**Comment by jjamminjim** [comment]
Can to reproduce this error. Closing
