### ISSUE TITLE
(#165) Refund amounts on IPAD are coming back as amount collected in the x-tape report.

### ISSUE THREAD

**Issue by archanamckesson** [rxtrax/tracking#135]
When we are collect the amount on the IPAD and click on cancel, the amount gets processed as a refund.
After finishing the payment on the IPAD and closing the virtual drawer in Psv, the amount on the X-tape displays even the refund amount as amount collected.

Expected:Only amount paid should be reflected in X tape.
[#110178668_Response.txt](https://github.com/rxtrax/tracking/files/758895/110178668_Response.txt)

**Comment by brprashanth** [comment]
This is related to the refund transaction issue. If you refund, any payments assosciated with the transaction should be cleaned up. 
Looks like even after the refund was done, the RxTrax application was returning the payments.
