### ISSUE TITLE
(#164) select signature window-pick up signature screen has discrepancies.

### ISSUE THREAD

**Issue by archanamckesson** [rxtrax/tracking#136]
There are few discrepancies in the select signature window for pick up signature captured via RxTrax.

1.The flags are correctly displayed at times, other times its blank.
2.The time column of the pick up signature screen shows null values some times.
![162](https://cloud.githubusercontent.com/assets/25255271/22709884/661701f8-ed49-11e6-8a1c-90bdbe9f9d34.JPG)
![162_2](https://cloud.githubusercontent.com/assets/25255271/22709889/698d9018-ed49-11e6-98d4-bc11907dc01c.png)

**Comment by jjamminjim** [comment]
@brprashanth : If #1 above concerns the acknowledgment null values and sync ordering issue, this is fixed in the current release. #2 above seems to be a pharmaserve issue. If that is not the case please submit a separate issue that details the issue from the RxTrax perspective. Thanks

**Comment by brprashanth** [comment]
@jjamminjim, 2 is not a pharmaserv issue. If the the acknowledgement flag comes back consistently, the date time of when it came also will be recorded. So it will fix indirectly.
@archanamckesson can you please validate if the issues mentioned above is not occurring anymore.

**Comment by brprashanth** [comment]
The issue seem to be fixed.

**Comment by brprashanth** [comment]
This is failing now and we are getting the acknowledged flag on the build 4.0.0 (0.25.0)

**Comment by brprashanth** [comment]
This has been fixed.
