### ISSUE TITLE
(#163) Mobile delivery- Discrepancies with RxTrax routes displayed in POS preference.

### ISSUE THREAD

**Issue by archanamckesson** [rxtrax/tracking#137]
It's observed that few of the routes which are archived in RxTrax, are showing up under the primary route field in POS.
Few of the routes which we move from ‘Archived’ to ‘Active’ in RxTrax are also not displaying under primary routes in POS.

I have attached the screenshots for a clear understanding of the issue.
[Routes in RxTrax and POS.docx](https://github.com/rxtrax/tracking/files/758909/Routes.in.RxTrax.and.POS.docx)

**Comment by brprashanth** [comment]
This may have been fixed already.

**Comment by brprashanth** [comment]
@archanamckesson, request you to validate the same and confirm.

**Comment by RobinGK** [comment]
This was validated and closed in Pharmaserv. This can now be closed.
