### ISSUE TITLE
(#161) Pharmaserv has a limit to the number of Credit/Debit cards allowed per transaction of 3. See message below 

### ISSUE THREAD

**Issue by RobinGK** [rxtrax/tracking#138]
(#161) Pharmaserv has a limit to the number of Credit/Debit cards allowed per transaction of 3.  Is this possible in RxTrax to display a message like this?

**Comment by RobinGK** [comment]
![3 card limit](https://cloud.githubusercontent.com/assets/24940848/22710146/3fa0a050-ed4a-11e6-93a3-cdc093f1f386.png)

**Comment by jjamminjim** [comment]
Does this include Gift cards?

**Comment by jjamminjim** [comment]
I understand that this limit is being set via `card_limit` on `payment_config`?

**Comment by brprashanth** [comment]
Yes Jim. We are sending the card_limit on our patch request to pharmacy.
We will include the Gift Card limit as well. Thanks.
