### ISSUE TITLE
(#162) Pharmaserv also has  limit of 1 Gift Card per transaction.  Please see below. 

### ISSUE THREAD

**Issue by RobinGK** [rxtrax/tracking#139]
(#162) Pharmaserv also has  limit of 1 Gift Card per transaction.  Please see below. 
![1 gift card limit](https://cloud.githubusercontent.com/assets/24940848/22710229/8854680e-ed4a-11e6-8306-80a03eaea067.png)

**Comment by jjamminjim** [comment]
Like `card_limit` on `payment_config`, let's set this limit through `gift_card_limit`. OK?

**Comment by jjamminjim** [comment]
@brprashanth How does one limit the # of gift cards? I don't know it is a gift card until the transactions is complete.

**Comment by jjamminjim** [comment]
@brprashanth I noticed you took PreBeta off this issue? Is this not needed for beta now? Do you have a suggestion for how to limit the # of gift cards when I don't know it is a gift card until the transactions is complete?

**Comment by brprashanth** [comment]
@jim, we had triage meeting today and Rob will share you an update.
This will be a known issue and will be training thing. The driver should basically not allow the customer to use the 2nd gift card.

**Comment by jim** [comment]
Hi! @jim is not who you think it is 😄
