### ISSUE TITLE
(#167) Return acknowledgements as "true"/acknowledged for the optional acknowledgement questions.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#141]
Based on our discussion today, for the acknowledgements, 
*1. if we send the "IsRequired" flag as true, the 'Yes/No' buttons will appear.
*2. if we send the "IsRequired" flag as false, the 'Yes/No' buttons will not appear and all messages will appear one below the other and customer should "Agree" to proceed (Basically he is agreeing on everything).

**Regarding the Responses received:**
1. For the *1 above, the response should return "yes/no" based on what the customer selected.
2. For the *2 above, the response should return all acknowledgements as "acknowledged" as there is no other choice for the customer other than "Agree" (click "Agree" button).

**Comment by RobinGK** [comment]
Also the heading of the HIPPA message screen should be Acknowledgements -  Please remove the word Required.

**Comment by brprashanth** [comment]
The issue seem to be fixed.

**Comment by brprashanth** [comment]
This is failing on the build 4.0.0 (0.25.0)

**Comment by brprashanth** [comment]
This has been fixed.
