### ISSUE TITLE
(#168)  EMV cards.  There is a requirement that when an EMV card is decline we must print a decline receipt that includes the Terminal Denial Code. 

### ISSUE THREAD

**Issue by RobinGK** [rxtrax/tracking#142]
(#168)  EMV cards.  There is a requirement that when an EMV card is decline we must print a decline receipt with the Terminal Denial Code so the customer can call in and find out why.   All 4 types of cards AMEX, DISC. VISA and MasterCard all require this. There is one difference in the receipt for AMEX and DISC. They require the expiration date to also print.  I will attach 1 example now and then get one with expiration date . We should be ale to add it to the existing receipt. But this is only EMV chip cards. 
![decline emv](https://cloud.githubusercontent.com/assets/24940848/22839206/80c30db8-ef96-11e6-8434-daa496899b11.jpg)

**Comment by brprashanth** [comment]
This is required by RxTrax to clear the Cayan's certification requirements.

**Comment by jjamminjim** [comment]
@brprashanth Any chance I can get a failed EMV response?

**Comment by jjamminjim** [comment]
App and api work is done. Email service is not yet running, Will be done by end of tomorrow.

**Comment by brprashanth** [comment]
The application is no generating the Email when there was a decline. I just ran a transaction with $41 on an TEST EMV card and it declined. However, no email was generated.
Receipt number 812352

**Comment by brprashanth** [comment]
**It should do one of the below:**
1.	If the email address is available : Automatically generate the Email with the Decline Receipt with the given information.
2.	If the email address is not available : It should prompt the “Email Address” prompt window (that we popup when we normally “Finish” a transaction) to get the email address from the user to send the email receipt. 

**To Simulate/Get the “Decline” on the EMV Cards:**
•	Use any EMV Test Card 
•	Enter a transaction for the amount $41. The test system is built-in to return a “decline”.  
•	This decline should generate the Email Receipt as said above.
I did few tests with the Receipt id: 812352 and it did not generated the Decline Receipt.
Please refer the transactions made on 812352.

**Comment by jjamminjim** [comment]
Email service for failed EMVs is now up and running. However our EMV card does not decline with $41.00.  I am closing this and requesting that @brprashanth, @RobinGK verify. Thanks!

**Comment by brprashanth** [comment]
•	Please check the Receipt Id # 814257. I did two EMV transactions that Declined - $41 each. The application did not generated email.
•	The Delivery had the email id: Prashanth.bala@mckesson.com when the Request was created.
•	I only received the completed receipt after finishing my delivery, did not received the “Decline Receipt” at all.

![cayan portal](https://cloud.githubusercontent.com/assets/8714134/23808502/7f7027f0-05a0-11e7-9a6c-fca558b16b37.png)

![img_5740](https://cloud.githubusercontent.com/assets/8714134/23808561/b0daf270-05a0-11e7-95a2-12b7d9349dfa.PNG)

**Comment by jasonmadrid** [comment]
OK, other than having the same formatting issues as seen in #133, the sending is working properly now.  We were able to test full circuit with the device this time.  Will be fixing all the formatting issues for both types of receipts with #133.
