### ISSUE TITLE
(#169) 7.6.0- Mobile delivery- RxTrax Receipt doesn't display Rx amount as QHP (after you remove an Rx and add a new one)

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#143]
RxTrax doesn't include Rx amount under QHP at the footer note on the Receipt.
**Note: This works in normal cases. However, it fails when you Remove an Rx and add a new one.**

**Steps:**
1.Add a QHP item (2.50$) to delivery transaction.
2.The receipt in the RxTrax app displays the correct QHP amount (2.50$).
3.Retrieve the receipt and add an Rx (1.00$).
4.The receipt in the RxTrax app displays the QHP amount as 2.50$. It doesn't take the Rx into consideration.

As per POS log, the request contains correct Health Care amount, but the amount displayed under QHP items in the receipt is incorrect. Essentially an Rx is a QHP by default.

The QHP total at the bottom of the receipt should include both QHP amount and Rx Amount

[Request file.txt](https://github.com/rxtrax/tracking/files/767553/Request.file.txt)

![image](https://cloud.githubusercontent.com/assets/8714134/22840176/df6de476-efa2-11e6-86cd-5bf8d435b746.png)

**Comment by brprashanth** [comment]
Note that when the issue happens it displays the old QHP amount. In the example above it is display $2.50 as the QHP. This is the old QHP value before we sent the Update request with an new QHP item.

**Comment by jjamminjim** [comment]
The nonprescription bhp item is now flagged via the `is_qhp` field in Prescription record.

**Comment by brprashanth** [comment]
This has been fixed now.
