### ISSUE TITLE
RxTrax Sandbox portal  - Dashboard not displaying.

### ISSUE THREAD

**Issue by sindhujan-sid** [rxtrax/tracking#147]
Issue : RxTrax sandbox portal - Dashboard is not displaying (attached screen shot below)

Impact: Not able to access any Rx's processed from Enterprise Rx to RxTrax in the RxTrax sandbox.

![dhayalan](https://cloud.githubusercontent.com/assets/25191682/23066593/5bcbc8c8-f541-11e6-97d8-f7aec9a27671.PNG)

**Comment by sindhujan-sid** [comment]
@jasonmadrid  Please look into the above issue.

**Comment by jasonmadrid** [comment]
@sindhujan-sid can you clear your browser cache and try again?  If that doesn't work, can you open your browser console and see if you're getting any errors?

**Comment by sindhujan-sid** [comment]
@jasonmadrid , Tried clearing the browser cache , Same issue is happening. 

Below is the screenshot of the browser console : 

1)Internet Explorer :
Internet Explorer version : 11.0.9600.18426

![browser console](https://cloud.githubusercontent.com/assets/25191682/23163291/cd3de806-f857-11e6-886d-3ef1f6d5b7af.PNG)

2)Google Chrome : 
Version 56.0.2924.87 (64-bit)

![browser console - gc](https://cloud.githubusercontent.com/assets/25191682/23163608/178a0830-f859-11e6-85cd-4542a93617d5.PNG)

**Comment by jasonmadrid** [comment]
@sindhujan-sid Could you give me the username/password you're using?
