### ISSUE TITLE
Status of Rx in ERx application is not changing the status to sold when making it as delivered in Rx Trax using IPAD

### ISSUE THREAD

**Issue by sijohnj** [rxtrax/tracking#148]
**Summary:** Status of Rx in ERx application is not changing the status to sold when making it as delivered in Rx Trax using IPAD.

**Expected Result:** When the Rx is delivered using Rx Trax application in IPAD, the status of the ERx application should move to Sold.
**Actual Result:** Currently the Rx number is remaining with earlier status and not moving to sold.

**Message:** 
{"external_id":"rxtrax-ERX-NDCQ34-BUT-deliveries-10292045206&23213804","delivery_date":1487548800,"deliver_before":1487575620,"address1":"26TH MAIN","city":"SCHENECTADY","state":"NY","postal_code":"12345","collect_amount":2084.4,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":true,"cancelled_on":null,"recipient":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213804","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"EARFA","city":"SCHENECTADY","state":"NY","postal_code":"12345","country":"USA","facility":false,"is_archived":false},"external_route_id":"585a7ee46c209","delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163117206","quantity":"3.0","fill_number":0,"total_price":2084.4,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163117206","rx_number":"004109","description":"BOTOX 100UNIT SOLR","customer":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213804","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"EARFA","city":"SCHENECTADY","state":"NY","postal_code":"12345","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":false}],"is_archived":false}

**Comment by jasonmadrid** [comment]
@sijohnj Looks like you have a webhook configured with no url to call back to.

**Comment by sijohnj** [comment]
@jasonmadrid Please look into the same.

**Comment by sijohnj** [comment]
@jasonmadrid Thank you, Jason. The issue seems to be working fine now.
