### ISSUE TITLE
(#181) The Item that was delivered and completed is not getting synchronized even after 120 minutes

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#157]
(#181) The Item that was delivered and completed is not getting synchronized even after 120 minutes

It does not happen often, but happens once in a while. 
If this happens, it does not sync at all.
Note: I delivered few other items later and all those came back. This particular item is showing that “Yellow” “Dot” icon indicating it is yet to synchronize.
We have seen this before, since this reoccurred today we are listing here for tracking purposes.

**Delivery Id : 1101667**
Using QA Account - Api Key: hh09WTF1hT2YYYMRkRdmwSG6s4ojG4f1nK64dKSFYPSAg5Ql9w

------------------------------------------------------------------------------------------

Jason,

Request you to let us know if there was any particular reason for the delivery took so long to arrive?
I just cross checked our database and the item arrived back to our system around 7 hrs late. 
Please note that if the data do not arrive to our Pharmacy within the same day (EOD) for some reason, it will lead to reconciliation issues and Support Calls.

Timeline:
09-12 am : 1st post
09-24 am : 2nd update
09-39 am : get call returned null for transaction (see attachment)
16-07 pm : sync happened. (7 hours late)
------------------------------------------------------------------------------------------
[09-24 am 2nd update.txt](https://github.com/rxtrax/tracking/files/817806/09-24.am.2nd.update.txt)
[09-39 am get call returned null.txt](https://github.com/rxtrax/tracking/files/817804/09-39.am.get.call.returned.null.txt)
[16-07 pm sync happened.txt](https://github.com/rxtrax/tracking/files/817805/16-07.pm.sync.happened.txt)
[09-12 am 1st post.txt](https://github.com/rxtrax/tracking/files/817803/09-12.am.1st.post.txt)
![image](https://cloud.githubusercontent.com/assets/8714134/23567767/46cca206-002e-11e7-8d5f-48e0677f1032.png)

------------------------------------------------------------------------------------------

![img_5686-1](https://cloud.githubusercontent.com/assets/8714134/23513944/24de62c6-ff3c-11e6-95d1-b0dd9f62b289.png)
![img_5687](https://cloud.githubusercontent.com/assets/8714134/23513951/2910802c-ff3c-11e6-8a58-7e3309525680.PNG)
![img_5688](https://cloud.githubusercontent.com/assets/8714134/23513950/29105c00-ff3c-11e6-81b7-cb71a1f164af.PNG)

**Comment by brprashanth** [comment]
Jason,

Request you to let us know if there was any particular reason for the delivery took so long to arrive?
I just cross checked our database and the item arrived back to our system around 7 hrs late. 
Please note that if the data do not arrive to our Pharmacy within the same day (EOD) for some reason, it will lead to reconciliation issues and Support Calls.

Timeline:
09-12 am  1st post
09-24 am 2nd update
09-39 am  get call returned null for transaction (see attachment)
16-07 pm  sync happened. (7 hours late)

**Comment by jasonmadrid** [comment]
We are tentatively closing this, though it needs much more testing.  We have implemented better transactional syncing from app to server, and identified and fixed the correlated issues #64 #73

**Comment by brprashanth** [comment]
From: Bala, Prashanth 
Sent: Tuesday, March 21, 2017 3:39 PM
To: 'Jason Madrid'
Cc: Jim Boyd; Walt Brooks; Akkaraju, Ravinder; Gieseck-Kiekens, Robin; Vaithilingam, Sudha; Konanur, Hamsa; Kumar, Prasun
Subject: RE: (#181) An Item that was delivered and completed is not getting synchronized even after 120 minutes
Importance: High

Good afternoon Jason, Jim,

We are facing this issue again.  
The Delivery ID# 1102050 (on QA API Key) was completed today at around noon. However, it has not synchronized even after 2 hrs. We are reopening this issue.
Note: This was the exact transaction that crashed the application. (Have sent a separate email)

I have attached the response we received even after 2 hours since it was completed.
The behavior is still the same we have explained below:
1.	The status is still marked “scheduled” #1102050.
2.	Why is RxTrax returning an incomplete response?. We had discussed this issue earlier couple of times (Issue #111). Issue #111 is currently closed.  Even recently we were told that this has been fixed.
Actually, if we look at the response, we also got responses for the following deliveries "1102048", "1102054","1102055", "2101212". (see attachment)
None of these have been “delivered”. They are coming back to us with the “scheduled” status.
Since this is occurring again, we are reopening this issue.
3.	The Payment types are again coming back as blank (please see the attachment). Screenshot below
Issue #191 was fixed and closed. Now, I see the same behavior on this incomplete transaction.

**Comment by brprashanth** [comment]
[1102050 QA Api Key.txt](https://github.com/rxtrax/tracking/files/859306/1102050.QA.Api.Key.txt)

**Comment by brprashanth** [comment]
not seeing this issue any more. removing the tag.
