### ISSUE TITLE
Route is getting displayed as ‘General’ instead of specified route for active item , When other item in the order is cancelled.

### ISSUE THREAD

**Issue by sijohnj** [rxtrax/tracking#165]
Processed 2 items in order with a specified route 'ABC'  to ready. Cancelled one item in order in ready status and other item is sent to RxTrax with route as 'ABC' in ready status. But in RxTrax sandbox the route is shown as 'General'.

**for the1st item :**

{"external_id":"rxtrax-ERX-NDCQ34-BUT-deliveries-10292056930&23213801","delivery_date":1489104000,"deliver_before":1489135260,"address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","collect_amount":70797.31,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":false,"cancelled_on":null,"recipient":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"external_route_id":"5886fbf1d8ed8","delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163129550","quantity":"30.0","fill_number":0,"total_price":70797.31,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163129550","rx_number":"004135","description":"HUMIRA 10MG/0.2ML PSKT","customer":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":false}],"is_archived":false}

**for 2nd item:**

{"external_id":"rxtrax-ERX-NDCQ34-BUT-deliveries-10292056930&23213801","delivery_date":1489104000,"deliver_before":1489135260,"address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","collect_amount":71075.15,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":false,"cancelled_on":null,"recipient":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"external_route_id":"5886fbf1d8ed8","delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163129551","quantity":"50.0","fill_number":0,"total_price":277.84,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163129551","rx_number":"004136","description":"KALETRA 100-25MG TABS","customer":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163129550","quantity":"30.0","fill_number":0,"total_price":70797.31,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163129550","rx_number":"004135","description":"HUMIRA 10MG/0.2ML PSKT","customer":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":false}],"is_archived":false}

**cancel request :**

{"external_id":"rxtrax-ERX-NDCQ34-BUT-deliveries-10292056930&23213801","delivery_date":1489104000,"collect_amount":277.8399999999965,"cancelled_on":null,"delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163129551","fill_number":0,"total_price":0.0,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163129551","rx_number":"004136","external_customer_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213801","is_archived":false},"is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163129550","fill_number":0,"total_price":0.0,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163129550","rx_number":"004135","external_customer_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213801","is_archived":true},"is_archived":true}],"external_recipient_id":"rxtrax-ERX-NDCQ34-BUT-patient-23213801","is_archived":false}

**Actual Result:** 
The specified route is not getting displayed in the Rx Trax application when one item is cancelled where the route is moving to the General route of its own and not of the user selected through  ERx application.

**Expected Result:**
The specified route selected in the ERx application should get displayed in the Rx Trax application when one item is cancelled.

**Comment by sijohnj** [comment]
@jasonmadrid Please look into the same.

**Comment by LakshmipriyaThangamuthu** [comment]
@sijohnj  - We have taken care of this issue from ERx. Changes will be available in tomorrow's Build.

This issue is no longer applicable.
Please close this.

**Comment by sijohnj** [comment]
Thank you @jasonmadrid
