### ISSUE TITLE
(#53) Provide Ordered Sequence Number On Payment Transactions

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#18]

**Comment by jasonmadrid** [comment]
One possible workaround right now is the created_on field on the Transaction record, which indicates the order in which they were created and processed by the device.

**Comment by pablo57** [comment]
Created new Transaction.Sequence field.

**Comment by jasonmadrid** [comment]
Waiting on iOS portion.

**Comment by brprashanth** [comment]
Priority elevated to High.
