### ISSUE TITLE
(#211) 500 Unknown Internal Error  - Regression issue after the fixes to issue #117  

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#192]
1.	Happens when invalid API key is provided, we are getting the below JSON response. 
2.	We need a specific error code for the same. Below it is throwing Unknown error and .
3.	Logged issue #211.

```
{
        "success": false,
        "codes": [500],
        "data": {
                        "error_instance": "58e2452cbc16f594105809"
        },
        "debug": {
                        "errors": ["500 - An unknown internal error has occurred. Rx Trax support has been notified."]
        }
}
```

**Comment by jasonmadrid** [comment]
This is fixed.  FYI, when you see this, it means the API is in an error state, much like a crash in the app, and that a problem isn't handled.  We don't intend for callers to ever see this, but it can happen due to a bug.

**Comment by brprashanth** [comment]
I'm getting confused. Whatever the case may be the application/API should return back a valid response.
This is like it coming back with some random error and application has no clue on what has happened.

**Comment by jasonmadrid** [comment]
This was a bug.  It means the API failed at the code level in a way we didn't expect.
