### ISSUE TITLE
(#211)  Issue today with Cancelling a transaction.  A little bit different than the other ones written up. 

### ISSUE THREAD

**Issue by RobinGK** [rxtrax/tracking#194]
Today I have done at least 3 voids and all I get is a blank screen with he heading Refunding payments.  And it just sits there for as long as I leave it there. No error message and no way out of the screen except killing the app.  Funny thing is the voids works if I turn off the Cayan device and try to cancel the transaction it will complete (which is the original test I was trying to validate.) 
![void screen stuck forever](https://cloud.githubusercontent.com/assets/24940848/24625662/c36c5b64-187d-11e7-9714-03f23ededee9.jpg)
I can add a print screen.

**Comment by brprashanth** [comment]
This happened to me even today. Delivery Id 621129. (Dev Api **Key).**
Attaching the screenshot:

![image](https://cloud.githubusercontent.com/assets/8714134/24680592/e363ae96-1967-11e7-92e3-16607d4faf58.png)

**Comment by jjamminjim** [comment]
This happened in association with zero dollar transactions

**Comment by RobinGK** [comment]
This was tested today and is working fine.  build # 0.43.0
