### ISSUE TITLE
(#213) Getting "Max Cards exceeded error even when only one or two cards were used

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#195]
(#213) Getting "Max Cards exceeded error" even when only one card transaction was used not the Total allowed Three Cards. (Max Card set to 3)

Happened for many deliveries both on QA/Dev API Key.
**Delivery Ids: Using Dev API Key**
621129
621128
781011 
781013

![image](https://cloud.githubusercontent.com/assets/8714134/24678348/95d05cd0-1960-11e7-9128-2af3841894e1.png)

**Comment by jjamminjim** [comment]
I believe this had to do with zero dollar transactions.

**Comment by brprashanth** [comment]
the issue is occuring again and have reopened the issue

**Comment by brprashanth** [comment]
Delivery Id # 8104248
Only two card transactions were made, both were partials. 
Received $0.0 and Max Credit card errors both.

![img_5962](https://cloud.githubusercontent.com/assets/8714134/24782842/148cc864-1b1f-11e7-878f-2b3735f71a56.PNG)
![img_5963](https://cloud.githubusercontent.com/assets/8714134/24782843/14b1ea2c-1b1f-11e7-8f5b-209e9e3254a3.PNG)
![img_5964](https://cloud.githubusercontent.com/assets/8714134/24782844/14d6902a-1b1f-11e7-86c5-204b46af6873.PNG)
![img_5961](https://cloud.githubusercontent.com/assets/8714134/24782845/14fbf19e-1b1f-11e7-96f9-3ba9156c55a9.PNG)

**Comment by RobinGK** [comment]
So far this looks to be closed.  I have been using partials and cancelled.   RxTrax v4.1.0 (0.50)
