### ISSUE TITLE
(#214) Getting Amount $0.0 printed on the receipts

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#196]
(#214) Getting Amount $0.0 printed on the receipts - not sure from where it is getting printed.

It is occurring on both Emailed Receipt and IPAD Receipt

Delivery Id 621129. 
It is happening consistently with this delivery. I tried refund and making new payments but the $0.0 would not go away.

![image](https://cloud.githubusercontent.com/assets/8714134/24680396/2dc4061c-1967-11e7-9d44-77b9d1913461.png)

![image](https://cloud.githubusercontent.com/assets/8714134/24680422/3dda579a-1967-11e7-8449-a69c49357956.png)

![image](https://cloud.githubusercontent.com/assets/8714134/24680435/4b5939ae-1967-11e7-80e9-bf5338ae2d66.png)

**Comment by brprashanth** [comment]
@jjamminjim, the amount $0.0 occured again. This was during a normal credit card operation when receiving partials credit approval. 

Delivery Id 8104351

![image](https://cloud.githubusercontent.com/assets/8714134/24722078/bda03c18-1a18-11e7-87ad-d7553e5cef3a.png)

**Comment by jjamminjim** [comment]
I think I got this fixed, although your scenario may be different then the one I was able to reproduce.  Please let me know if you see more of this.

**Comment by brprashanth** [comment]
the issue is occuring again and have reopened the issue

**Comment by brprashanth** [comment]
Delivery Id # 8104248
Only two card transactions were made, both were partials. 
Received $0.0 and Max Credit card errors both.

![img_5962](https://cloud.githubusercontent.com/assets/8714134/24782842/148cc864-1b1f-11e7-878f-2b3735f71a56.PNG)
![img_5963](https://cloud.githubusercontent.com/assets/8714134/24782843/14b1ea2c-1b1f-11e7-8f5b-209e9e3254a3.PNG)
![img_5964](https://cloud.githubusercontent.com/assets/8714134/24782844/14d6902a-1b1f-11e7-86c5-204b46af6873.PNG)
![img_5961](https://cloud.githubusercontent.com/assets/8714134/24782845/14fbf19e-1b1f-11e7-96f9-3ba9156c55a9.PNG)
