### ISSUE TITLE
(#216) After Refunding/VOID the FINISHED Button did not got enabled.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#199]
(#216) After Refunding/VOID the FINISHED Button did not got enabled. No way to go back the application.

Delivery ID 621129. Tried three times but the Refund Screen does not complete at all and FINISH Button disabled. Unable to exit now, waited for more 10-15 minutes and nothing happens.
Similar to issue #194 

Also observed, it did not say "Refunds Completed!" that it will normally do.

![img_5935](https://cloud.githubusercontent.com/assets/8714134/24681685/b2ca407e-196c-11e7-823d-f7da117252b9.PNG)
![img_5938](https://cloud.githubusercontent.com/assets/8714134/24681687/b2f3ec62-196c-11e7-9343-cf7ac900feae.PNG)
![img_5947](https://cloud.githubusercontent.com/assets/8714134/24681688/b32c0ce6-196c-11e7-89fb-48ec4ba03ea8.PNG)

**Comment by jjamminjim** [comment]
This was associated with the zero dollar transaction items.
