### ISSUE TITLE
(#63) 500 Error on iPad After Making Cayan Payment

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#20]
![image](https://cloud.githubusercontent.com/assets/2541528/21629306/4fa356ae-d1e4-11e6-8e15-343d8996b27d.png)
![image](https://cloud.githubusercontent.com/assets/2541528/21629333/902ec8fc-d1e4-11e6-895e-447fec5792e0.png)

**Comment by brprashanth** [comment]
![500 errors](https://cloud.githubusercontent.com/assets/8714134/21696591/269917b2-d365-11e6-960b-95abf45f0eb3.png)
