### ISSUE TITLE
(#223) RxTrax - Items are not getting delivered - coming back as "Verifying"

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#206]
We were running some tests today and found this issue while trying to Sync.  
We completed few deliveries on the IPAD normally (regular deliveries, not recovery steps).  Apparently, the status of delivered item is not being moved to “Delivered” status but getting stuck this new status “Verifying”

The status of the delivered receipt is not coming back as "Delivered" when we deliver any item on the IPad. The status comes back as “Verifying” instead. 
Please find the screenshot below and json file attached for reference. Also, we have checked with QA teams and even they are facing the same issue. (Happening on both DEV and QA API key)
![image](https://cloud.githubusercontent.com/assets/8714134/25135223/1e81c790-2428-11e7-9263-5ea0679fc3dd.png)

Because of this issue the below functionalities are not working on our POS. The status was returning properly till yesterday and this new issue happens only when the receipt is delivered. 

Issues facing now with this change:
1.	HIPAA Acknowledgments and amounts paid will not be captured as the status is not coming back as “delivered”.
2.	Item stays in our Delivery Queue even after payments as the status is not getting changed to “Delivered”.  Receipt will not be moved to delivered receipt tab.
3.	Any of the reports will not capture the amount collected by the delivered receipts.

Also, request you to keep us in loop if you are making any new additions to the API. 
•	At this moment we are seeing the new “Verifying” status and the “Verified_on” date field. Please let us know if we need to expect anything with regards to the same.
•	The documentation is not updated with the same.

**Comment by RobinGK** [comment]
Close this and see # 225 issue for Sync calls.
