### ISSUE TITLE
Status of Rx in ERx application is not changing to sold when Rx is delivered/Sold in Rx Trax using IPAD. 

### ISSUE THREAD

**Issue by sindhujan-sid** [rxtrax/tracking#207]
Summary: 
Status of Rx in ERx application is not changing to sold when making it as delivered in Rx Trax using IPAD.

Expected Result: 
When the Rx is delivered using Rx Trax application in IPAD, the status of Rx should move to Sold in the ERx application 

Request Message:
 {"external_id":"rxtrax-ERX-NDCQ14-YUC-deliveries-10106386848&6916445","delivery_date":1492560000,"deliver_before":1492596540,"address1":"SDFSD","city":"GENERAL ELECTRIC","state":"NY","postal_code":"12345","collect_amount":87931.42,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":false,"cancelled_on":null,"recipient":{"external_id":"rxtrax-ERX-NDCQ14-YUC-patient-6916445","first_name":"NOTBEEN","last_name":"ASKED","home_phone":"1111111111","address1":"SDFSD","city":"GENERAL ELECTRIC","state":"NY","postal_code":"12345","country":"USA","facility":false,"is_archived":false},"external_route_id":"5886fee495cd9","delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ14-YUC-delivery_prescriptions-10072206463","quantity":"30.0","fill_number":0,"total_price":87931.42,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ14-YUC-prescription-10072206463","rx_number":"004317","description":"HUMIRA 10MG/0.2ML PSKT","customer":{"external_id":"rxtrax-ERX-NDCQ14-YUC-patient-6916445","first_name":"NOTBEEN","last_name":"ASKED","home_phone":"1111111111","address1":"SDFSD","city":"GENERAL ELECTRIC","state":"NY","postal_code":"12345","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"rxtrax-ERX-NDCQ14-YUC-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":false},{"external_id":"rxtrax-ERX-NDCQ14-YUC-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":false}],"is_archived":false}

**Comment by jasonmadrid** [comment]
Should be good to go now.  Deployment issue in your sandbox.
