### ISSUE TITLE
Issue with saving the RX information at RxTrax side for one of our test customers.

### ISSUE THREAD

**Issue by gopiraj24** [rxtrax/tracking#209]
We are getting a 500 response on send a delivery message. This is a high priority item. Please find the below response.

500 response->{"success":false,"authorized":false,"code":500,"data":{"error_instance":"5901fd3ed5ea0018230122"},"message":"Unknown error.  Rx Trax developers have been notified."}

**Comment by gopiraj24** [comment]
@jasonmadrid  Let me know if you need more information.

**Comment by brprashanth** [comment]
Hi @gopiraj24 , did this happened in any particular scenario or did it occurred for a random delivery?
Is this reproducible? If possible, please share the details. We will try replicate in the Pharmaserv Environment. Thanks.

**Comment by gopiraj24** [comment]
@brprashanth  This issue is always reproducible. The scenario is basic - when submitting the delivery object with all the details ...we get a 500 response and the delivery does get persisted at RxTrax...only that the delviery_prescriptions are not getting persisted.

**Comment by jasonmadrid** [comment]
This is resolved.  It was a config issue on production.
