### ISSUE TITLE
One of the item is returning the dispense quantity as '-' in the IPAD application when separated from 2 item order.

### ISSUE THREAD

**Issue by sijohnj** [rxtrax/tracking#211]
Response for the Dispense quantity for one of the Rx is displayed as '-' in the IPAD application.

**Request message 1 sent to Rx Trax:**
{"external_id":"rxtrax-ERX-NDCQ34-BUT-deliveries-10292087888&23264207","delivery_date":1494547200,"deliver_before":1494580740,"address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","collect_amount":7374.72,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":true,"cancelled_on":null,"recipient":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","first_name":"WINE","last_name":"CHRISTMAS","home_phone":"1111111111","address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","country":"USA","facility":false,"is_archived":false},"external_route_id":"585a7ee46c209","delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163147733","quantity":"3.0","fill_number":0,"total_price":7374.72,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163147733","rx_number":"004322","description":"HUMIRA 10MG/0.2ML PSKT","customer":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","first_name":"WINE","last_name":"CHRISTMAS","home_phone":"1111111111","address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":false}],"is_archived":false}

**Request message 2 sent to RxTrax:**

{"external_id":"rxtrax-ERX-NDCQ34-BUT-deliveries-10292087888&23264207","delivery_date":1494547200,"deliver_before":1494580740,"address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","collect_amount":14749.44,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":true,"cancelled_on":null,"recipient":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","first_name":"WINE","last_name":"CHRISTMAS","home_phone":"1111111111","address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","country":"USA","facility":false,"is_archived":false},"external_route_id":"582e27a053ecd","delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163147734","quantity":"3.0","fill_number":0,"total_price":7374.72,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163147734","rx_number":"004323","description":"HUMIRA 10MG/0.2ML PSKT","customer":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","first_name":"WINE","last_name":"CHRISTMAS","home_phone":"1111111111","address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163147733","quantity":"3.0","fill_number":0,"total_price":7374.72,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163147733","rx_number":"004322","description":"HUMIRA 10MG/0.2ML PSKT","customer":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","first_name":"WINE","last_name":"CHRISTMAS","home_phone":"1111111111","address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":false}],"is_archived":false}

**Request message 3 sent to RxTrax:**
{"external_id":"rxtrax-ERX-NDCQ34-BUT-deliveries-10292087888&23264207","delivery_date":1494547200,"collect_amount":7374.72,"cancelled_on":null,"delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163147734","fill_number":0,"total_price":0.0,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163147734","rx_number":"004323","external_customer_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","is_archived":false},"is_archived":false}],"external_recipient_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","is_archived":false}

**Request message 4 sent to RxTrax:**
{"external_id":"rxtrax-ERX-NDCQ34-BUT-deliveries-10292089800&23264207","delivery_date":1494547200,"deliver_before":1494580740,"address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","collect_amount":7374.72,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":true,"cancelled_on":null,"recipient":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","first_name":"WINE","last_name":"CHRISTMAS","home_phone":"1111111111","address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","country":"USA","facility":false,"is_archived":false},"external_route_id":"582e27a053ecd","delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-delivery_prescriptions-10163147733","quantity":"3.0","fill_number":0,"total_price":7374.72,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-BUT-prescription-10163147733","rx_number":"004322","description":"HUMIRA 10MG/0.2ML PSKT","customer":{"external_id":"rxtrax-ERX-NDCQ34-BUT-patient-23264207","first_name":"WINE","last_name":"CHRISTMAS","home_phone":"1111111111","address1":"AVENUE RD","city":"WASHINGTON","state":"DC","postal_code":"20500","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-BUT-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":false}],"is_archived":false}
![image 1](https://cloud.githubusercontent.com/assets/25052659/26000264/e674097c-3745-11e7-96d1-8bb06cc36889.png)
![image](https://cloud.githubusercontent.com/assets/25052659/26000265/e67e3442-3745-11e7-8a92-3e32191072fa.png)

**Comment by sijohnj** [comment]
@jasonmadrid Please look into the issue.

**Comment by jasonmadrid** [comment]
We've conducted a review of the API requests as described above.  The basic information in the sequence is as follows:

**request 1:  A delivery with one item**

| rx# | quantity |
| --- | --- |
| 004322 | 3.0 |

This displays on the device as expected.

**request 2: Resubmit the same delivery with two items**

| rx# | quantity |
| --- | --- |
| 004322 | 3.0 |
| 004323 | 3.0 |

This update also displays as expected, as two items with quantities.

**request 3: Resubmit the same delivery with one item**

| rx# | quantity |
| --- | --- |
| 004323 | - |

In this request, no quantity is provided in the request, so Rx Trax doesn't set one.  This is by design.  The API defines the delivery and its details exactly as they are presented in the latest request, so as to not let old details pass through, complicating the definition.  So in this case, the 2 items from the previous request are replaced with the one item in this request, with no quantity.

**request 4: Submit a new delivery with one item**

| rx# | quantity |
| --- | --- |
| 004322 | 3.0 |

Since the external id is different for this request than the previous 3, a new delivery is created with the one item as defined.

**Comment by sijohnj** [comment]
Thank you @jasonmadrid
