### ISSUE TITLE
On click of Back Arrow in the Browser user is taken out of the RxTrax Sandbox website

### ISSUE THREAD

**Issue by LakshmipriyaThangamuthu** [rxtrax/tracking#213]
Steps to Replicate

1) Have logged into the RxTrax Sandbox
2) in the Dash board, on today's date [05/15] selected cancelled & was able to see the cancelled deliveries
3) Now click back button in the browser
4) User will be taken to the Default Home page set in the Browser [for me it's Google]

![cancelled_item](https://cloud.githubusercontent.com/assets/25032786/26060244/12e84cc6-39a2-11e7-88bc-6fb218141b3e.jpg)

**Comment by LakshmipriyaThangamuthu** [comment]
@jasonmadrid - Can you please have a look into this issue

**Comment by jasonmadrid** [comment]
This is how the dashboard works.  We are not using browser navigation when working with the dashboard.  It's more of a widget.

**Comment by LakshmipriyaThangamuthu** [comment]
ok Thank you @jasonmadrid
