### ISSUE TITLE
RxTrax doesn't send the acknowlegments [EZ Caps & All Rx] back in the Response

### ISSUE THREAD

**Issue by LakshmipriyaThangamuthu** [rxtrax/tracking#215]
**_REQUEST SENT :_**

{"external_id":"rxtrax-ERX-NDCQ34-ERX-deliveries-10292090444&23213801","delivery_date":1494892800,"deliver_before":1494936919,"instructions":"TEST REP ACKNOWLEGEMENTS","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","collect_amount":0.13,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":true,"cancelled_on":null,"recipient":{"external_id":"rxtrax-ERX-NDCQ34-ERX-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"external_route_id":"58c2b456deda0","delivery_prescriptions":[{"external_id":"rxtrax-ERX-NDCQ34-ERX-delivery_prescriptions-10163148875","quantity":"5.0","fill_number":0,"total_price":0.13,"partial_fill_sequence":0,"prescription":{"external_id":"rxtrax-ERX-NDCQ34-ERX-prescription-10163148875","rx_number":"004121","description":"COLD & ALLERGY 4-10MG TABS","customer":{"external_id":"rxtrax-ERX-NDCQ34-ERX-patient-23213801","first_name":"A","last_name":"A","home_phone":"1111111111","address1":"350 SUNSET DR","city":"PITTSBURGH","state":"PA","postal_code":"15228","country":"USA","facility":false,"is_archived":false},"is_archived":false},"is_archived":false}],"acknowledgements":[{"external_id":"rxtrax-ERX-NDCQ34-ERX-acknowledgements-RX_ACK","text":"I am receiving all Rx's.","is_archived":false},{"external_id":"rxtrax-ERX-NDCQ34-ERX-acknowledgements-EASY_CAP_ACK","text":"I authorize easy open caps.","is_archived":false}],"is_archived":false}

**_RESPONSE RECEIVED_**

{"success":true,"authorized":true,"codes":[200],"data":[{"external_id":"rxtrax-ERX-NDCQ34-ERX-deliveries-10292090444&23213801","created_on":1494947979,"original_delivery_date":1494892800,"delivery_date":1494892800,"delivered_on":null,"device_id":null,"validating":false,"priority":null,"deliver_before":"12:15 pm","deliver_after":null,"instructions":"TEST REP ACKNOWLEGEMENTS","notes":null,"id_number":null,"id_photo_id":null,"recipient_photo_id":null,"signature_image_id":null,"reschedule":false,"en_route":false,"cancelled_on":null,"verified_on":null,"address":null,"address1":"350 SUNSET DR","address2":null,"address3":null,"city":"PITTSBURGH","state":"PA","postal_code":"15228","received_by":null,"collect_amount":0.13,"tax_amount":null,"collect_info":null,"amount_collected":null,"customer_receipt":null,"vendor_receipt":null,"receipt_email":null,"photo_id_required":true,"signature_required":true,"recipient_photo_required":true,"payment_required":true,"gps_accuracy":null,"latitude":null,"longitude":null,"number_to_deliver":null,"number_delivered":null,"sync_stamp":1494947979,"is_archived":false,"status":"scheduled","external_route_id":"58c2b456deda0","external_recipient_id":"rxtrax-ERX-NDCQ34-ERX-patient-23213801","external_driver_id":null}],"message":null,"debug":{"missing":{"optional":{"status":"string","page_size":"int","page_num":"int","sync":"int"}}}}

**Comment by LakshmipriyaThangamuthu** [comment]
@jasonmadrid  - Please have a look into this issue & let me know for any further Information.

Thanks

**Comment by gopiraj24** [comment]
@jasonmadrid  The response here is a response which we got back by using the get deliveries api using a external id and the _ext=ack params. The respnse does not include the acknowledgements.

**Comment by jasonmadrid** [comment]
@LakshmipriyaThangamuthu @gopiraj24 The delivery in question has not yet been completed.  We currently only attach the acknowledgements on the GET call for completed deliveries.

**Comment by LakshmipriyaThangamuthu** [comment]
@jasonmadrid  earlier we used to get acknowledgements, even though delivery is not completed.
Can we have this functionality back, as we need this for some certain scenario's before the delivery gets completed.

Thanks,

**Comment by jasonmadrid** [comment]
@LakshmipriyaThangamuthu That wouldn't be difficult. @brprashanth how would that affect Pharmaserv?

**Comment by LakshmipriyaThangamuthu** [comment]
Hi @jasonmadrid  - can you please update us on this.

Thanks
Cc : @gopiraj24

**Comment by brprashanth** [comment]
Hi @jasonmadrid, that should be fine. With the new changes with regards to Filter, I believe non-delivered items will not reach us prior. Technically should be fine.
However, we are not expecting any unseen regression issue.

**Comment by jasonmadrid** [comment]
@brprashanth @gopiraj24 @LakshmipriyaThangamuthu OK, we'll make the change today.  I will notify everyone when it is deployed to sandbox.

**Comment by jasonmadrid** [comment]
The change has been made and deployed to sandbox.
