### ISSUE TITLE
(#227) Receiving incompleted card payments with the status “Initiating” at the Transaction level” 

### ISSUE THREAD

**Issue by RobinGK** [rxtrax/tracking#216]
I was researching on the Delivery ID #110300114 that did not synchronize with the object reference error.
Looks like there is an issue at RxTrax side. They are sending an additional payment with the “Transaction” status as “INITIATING” (Not to be confused with the recent “Delivery” status).
This new status we are seeing is at the “Transaction” level. Also, the receipt stub indicating two card transaction, however the “Transaction” node shows three line items.
Please see the attached request object and screenshots. We are receiving an incomplete status “Initiating” with a completely different schema – That is why our deserializer logic is failing.

However, on the transaction Node in the response. As per our original discussion few months back, we had agreed with RxTrax that RxTrax will only send approved transactions only.
 
[json.txt](https://github.com/rxtrax/tracking/files/1005566/json.txt)

![2](https://cloud.githubusercontent.com/assets/8714134/26158897/827edb52-3af3-11e7-9293-4aa50030fc11.png)
![1](https://cloud.githubusercontent.com/assets/8714134/26158899/82c2fa4e-3af3-11e7-9e68-c1702f142eb0.png)

**Comment by brprashanth** [comment]
`		"transactions": [{
			"payment_type": "credit",
			"check_number": null,
			"sequence": null,
			"amount": 10.55,
			"receipt": null,
			"receipt_email": null,
			"request": null,
			"information": "{\"AccountNumber\":\"************4512\",\"EntryMode\":\"SWIPE\",\"ValidationKey\":\"4b6b9eae-d266-4276-a3a3-aafc75bbca71\",\"PaymentType\":\"VISA\",\"TransactionType\":\"SALE\",\"ErrorMessage\":\"\",\"TransactionDate\":\"5\\\/12\\\/2017 8:03:06 PM\",\"Status\":\"APPROVED\",\"Token\":\"710660364\",\"Cardholder\":\"FDMS TEST CARD   \\\/VISA\",\"AuthorizationCode\":\"OK861C\",\"AmountApproved\":\"10.55\",\"AdditionalParameters\":{\"FsaCard\":\"1\",\"SignatureData\":\"49,140^51,139^66,129^86,118^94,111^108,104^128,97^147,94^165,93^186,98^208,106^225,119^241,134^256,148^271,162^291,174^310,185^327,194^340,200^354,202^372,201^390,197^409,190^426,182^441,171^455,158^468,145^479,134^488,122^497,112^507,103^522,100^541,101^564,108^588,118^597,123^0,65535^~\",\"AmountDetails\":{\"RemainingCardBalance\":\"0.00\",\"Discount\":{\"Total\":\"0.00\"},\"Donation\":\"0.00\",\"Surcharge\":\"0.00\",\"Cashback\":\"0.00\",\"UserTip\":\"0.00\"}},\"ResponseType\":\"SINGLE\"}",
			"cancelled": false,
			"refunded": null,
			"refund_info": null,
			"sync_stamp": 1494619825,
			"created_on": 1494619332
		}, {
			"payment_type": "credit",
			"check_number": null,
			"sequence": null,
			"amount": 0,
			"receipt": null,
			"receipt_email": null,
			"request": null,
			"information": "{\"AmountApproved\":\"16.22\",\"Status\":\"INITIATING\",\"TransportKey\":\"0301397f-0a27-43cf-b308-0ade15fb7906\"}",
			"cancelled": false,
			"refunded": null,
			"refund_info": null,
			"sync_stamp": 1494619826,
			"created_on": 1494619675
		}, {
			"payment_type": "credit",
			"check_number": null,
			"sequence": null,
			"amount": 16.22,
			"receipt": null,
			"receipt_email": null,
			"request": null,
			"information": "{\"AccountNumber\":\"************7684\",\"EntryMode\":\"SWIPE\",\"ValidationKey\":\"3c332351-0e91-41b3-b2c4-ee63cd09d0e0\",\"PaymentType\":\"DISCOVER\",\"TransactionType\":\"SALE\",\"ErrorMessage\":\"\",\"TransactionDate\":\"5\\\/12\\\/2017 8:09:54 PM\",\"Status\":\"APPROVED\",\"Token\":\"710671540\",\"Cardholder\":\"CES  TEST JCB ACCT\\\/\",\"AuthorizationCode\":\"OK9646\",\"AmountApproved\":\"16.22\",\"AdditionalParameters\":{\"SignatureData\":\"336,98^335,102^334,115^329,130^322,140^315,149^309,159^300,166^291,174^271,180^248,183^227,183^205,181^178,176^150,168^121,158^90,144^60,132^42,122^31,114^27,108^25,105^30,100^44,91^76,80^112,69^156,56^207,43^256,36^310,37^365,41^419,50^470,61^511,75^546,92^570,109^585,123^592,137^594,151^590,165^575,180^550,193^518,205^487,212^421,216^384,216^347,215^309,215^274,213^244,212^213,210^180,209^149,205^117,202^76,197^0,65535^~\",\"AmountDetails\":{\"RemainingCardBalance\":\"0.00\",\"Discount\":{\"Total\":\"0.00\"},\"Donation\":\"0.00\",\"Surcharge\":\"0.00\",\"Cashback\":\"0.00\",\"UserTip\":\"0.00\"}},\"ResponseType\":\"SINGLE\"}",
			"cancelled": false,
			"refunded": null,
			"refund_info": null,
			"sync_stamp": 1494619826,
			"created_on": 1494619778
		}]`
