### ISSUE TITLE
Instrctions sent from ERx are present in the RxTrax portal but not in IPAD

### ISSUE THREAD

**Issue by LakshmipriyaThangamuthu** [rxtrax/tracking#217]
**Please find the image showing the instructions in the RxTrax portal**
![portal](https://cloud.githubusercontent.com/assets/25032786/26211031/0ff26f3c-3c0f-11e7-9950-754f152fa641.JPG)

**In IPAD**
![sandbox](https://cloud.githubusercontent.com/assets/25032786/26211078/3192c63c-3c0f-11e7-9817-854e704367cf.png)

**Comment by LakshmipriyaThangamuthu** [comment]
@jasonmadrid - can you please have a look into this issue.

**Comment by jjamminjim** [comment]
The instructions are there.  That text box is scrollable. Unfortunately the iPhone/iPad does not display scroll0bars when these controls are at rest.  I will try to make it a bit more obvious.
![simulator screen shot may 18 2017 11 43 18 am](https://cloud.githubusercontent.com/assets/71037/26215955/946544f6-3bbf-11e7-8c6c-75fb4ae26135.png)

**Comment by jjamminjim** [comment]
In the new Beta 48 release if their are Driver Instructions the text field will flash once to draw attention of the driver.
