### ISSUE TITLE
(#68a) Provide Ability To Disable Paging in API

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#22]

**Comment by pablo57** [comment]
Propose sending a page_size=0 to disable paging.

**Comment by jasonmadrid** [comment]
I'm reopening due to some development identified as incomplete.

**Comment by brprashanth** [comment]
@jasonmadrid  this is not working.

Please reopen this issue

{
  "success": true,
  "authorized": true,
  "code": 200,
  "data": [
    {
      "external_id": "1",
      "name": "LIVONIA",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1482490184,
      "is_default": false,
      "is_archived": false,
      "external_driver_id": null
    },
    {
      "external_id": "2",
      "name": "Farmington",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1482406499,
      "is_default": false,
      "is_archived": true,
      "external_driver_id": "57eaccbac11c7"
    },
    {
      "external_id": "31",
      "name": "Ann Arbor North",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1483624556,
      "is_default": false,
      "is_archived": false,
      "external_driver_id": null
    },
    {
      "external_id": "32",
      "name": "Halifax2",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1483961409,
      "is_default": false,
      "is_archived": false,
      "external_driver_id": null
    },
    {
      "external_id": "579a37926510f",
      "name": "General",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1480571997,
      "is_default": false,
      "is_archived": false,
      "external_driver_id": null
    },
    {
      "external_id": "5819e7c4e9d48",
      "name": "Testing",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1480055867,
      "is_default": false,
      "is_archived": true,
      "external_driver_id": null
    },
    {
      "external_id": "582304a998b36",
      "name": "Mckinsey",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1482491425,
      "is_default": false,
      "is_archived": false,
      "external_driver_id": null
    },
    {
      "external_id": "582441352543c",
      "name": "test",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1480055864,
      "is_default": false,
      "is_archived": true,
      "external_driver_id": null
    },
    {
      "external_id": "58341b67c96d7",
      "name": "New_route",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1480055858,
      "is_default": false,
      "is_archived": true,
      "external_driver_id": null
    },
    {
      "external_id": "583420002e309",
      "name": "wallstreet",
      "sunday": true,
      "monday": true,
      "tuesday": true,
      "wednesday": true,
      "thursday": true,
      "friday": true,
      "saturday": true,
      "sync_stamp": 1483709120,
      "is_default": false,
      "is_archived": true,
      "external_driver_id": null
    }
  ],
  "message": null,
  "missing": {
    "optional": {
      "external_id": "string",
      "page_size": "int",
      "page_num": "int",
      "sync": "int"
    }
  }
}

**Comment by brprashanth** [comment]
Im not getting all routes. It is limiting only 10 routes at a time. 
![image](https://cloud.githubusercontent.com/assets/8714134/21826808/5a169878-d75f-11e6-887f-45aba13c5bd4.png)

**Comment by jasonmadrid** [comment]
We didn't just disable page_size by default, as we felt that would cause unnecessary large requests in cases where they weren't useful (like deliveries).  You need to set `page_size=0` explicitly on your request.

**Comment by brprashanth** [comment]
Ok Sure. Please let us know if something like that is there on any of the fixes. If we have to some changes please keep us up to date. Thanks.

**Comment by brprashanth** [comment]
this has been validated to be fixed.
