### ISSUE TITLE
(#235) - While working on iPad it come up and said Syncing and sat there not allowing me to use iPad for over 20 minutes. 

### ISSUE THREAD

**Issue by RobinGK** [rxtrax/tracking#226]
I was working on the pad and at one point it come up over the delivery list with a icon saying Syncing and just sat there for over 20 minutes.  I cannot do any transactions. It started at 4:23 and it's now 4:47 and it's still running. Why is this happening on the iPad and interfering with deliveries?  Is there a setting somewhere? It lasted approximately 4:23-4:50
![syncing issues](https://cloud.githubusercontent.com/assets/24940848/26425050/84cbac24-40a1-11e7-911d-2f081911d193.jpg)

**Comment by RobinGK** [comment]
This appears to have been fixed and validated with RxTrax v4.1.0. (51)

**Comment by RobinGK** [comment]
I missed where the actual syncing takes place.   It is still coming up with the syncing ICON but it is only taking about 8 seconds.  Is this what it should be doing?  Syncing each time you close the directions and go back to the delivery screen?

**Comment by jjamminjim** [comment]
@RobinGK whenever the app returns from the background (as is the case when you come back from the map app via directions button) the app will reestablish it's sync connection with the server. This may bring up the `Syncing..` indicator if it takes long enough to establish the link. So this 8 second display is not unexpected.

**Comment by RobinGK** [comment]
Yes I will close it. I sorta figured that was the case just wanted to double check.  Thanks.
