### ISSUE TITLE
(#74) '3 Dash' Button Is Causing Multiple/Invalid Pins To Draw On Map

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#26]
![image](https://cloud.githubusercontent.com/assets/2541528/21629489/33a23c52-d1e6-11e6-82f9-711fbc090e85.png)

**Comment by jjamminjim** [comment]
There a just a bunch of deliveries on the same address. Deliveries that are at the same address display on the map unclustered (as seen in the image above).

**Comment by brprashanth** [comment]
This has been fixed now.
