### ISSUE TITLE
(#84) iPad Times Out Before Cayan Process Finishes

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#29]
The Rx Trax app on the IPAD times-out prematurely before the user signs on the Genius mobile device after inserting his credit card on the CHIP.
The IPAD should have wait time more than it takes for the genius mobile device to turn idle.
Currently, it is happening returning very soon (may be less than 30 seconds) and the payment made on the genius device is lost and 500 error appears on the RxTrax App

See item #63. Two issues here
1. The IPAD timeout prematurely.
2. The Customer was charged - refer merchantware portal.

![image](https://cloud.githubusercontent.com/assets/2541528/21629577/fde3c80a-d1e6-11e6-9a14-13481a28105f.png)

**Comment by jjamminjim** [comment]
Fixed! As of build 0.0.18, the iPad should not sleep while payment window is up.
