### ISSUE TITLE
(#85) Amount Field Should be Prepopulated/Fixed For Cayan Payments

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#30]
![image](https://cloud.githubusercontent.com/assets/2541528/21629611/32b29aa2-d1e7-11e6-91c6-ce498f839d4c.png)

**Comment by jasonmadrid** [comment]
Oops, this was already fixed.

**Comment by brprashanth** [comment]
This seems to be working. We have validated this. Please remove the **needs_verification** tag
We will let you know if in case we find any other issue regarding to the same.
