### ISSUE TITLE
(#87) Timeout Exception Recorded In Transaction Information Field

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#32]
We are getting time out exception for some records in the payment information due to which we are not able to proceed with de-serialization of payment information. Details are mentioned below. 

URL- https://api.sandbox.getrxtrax.com/v1/deliveries?api_key=anmdJdLYuYBe8U2qTARqrFjtB0uYQHUEkJnDmhsnsgJ4ucKVL7Zg&sync=1482761406&page_size=10&_ext=acks%2Ctxns&sync_id=112475
External Id- 110195

![image](https://cloud.githubusercontent.com/assets/2541528/21629677/c858c68a-d1e7-11e6-9003-d11a1f286917.png)

**Comment by jjamminjim** [comment]
@jasonmadrid : Not iOS I think. Api issue?

**Comment by jasonmadrid** [comment]
@jjamminjim No, look at the screenshot.  It's an iOS exception being recorded in the information field.

**Comment by jasonmadrid** [comment]
Turns out this is a cancelled transaction, and the error was recorded purposefully here.  Is that correct @jjamminjim?

**Comment by jjamminjim** [comment]
Yes that is correct!

**Comment by brprashanth** [comment]
This has been fixed now.
