### ISSUE TITLE
(#2) Delivery Status Field

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#33]
Single status field to communicate delivery status (delivered, cancelled, rescheduled, archived, etc.)

Status options in order:

archived
delivered
cancelled
reschedule
scheduled
en_route

**Comment by jasonmadrid** [comment]
Added en_route as a status value.  I believe it is the lowest priority status in order.

**Comment by pablo57** [comment]
Closing this now. However en_route was place on a higher priority than scheduled making scheduled the lowest in priority.

Status options in order:

archived
delivered
cancelled
reschedule
en_route
scheduled

**Comment by brprashanth** [comment]
This has been made available now.
