### ISSUE TITLE
(#70) deliver_before and deliver_after as time strings 

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#34]
Need to send and receive values through the Vendor API as valid time strings ('9:00 am') instead of unix timestamps.

**Comment by RyanNerd** [comment]
Will support time strings **or** timestamps for POST/PATCH. GET will always be in string format.

**Comment by jasonmadrid** [comment]
@RyanNerd Sounds good.

**Comment by brprashanth** [comment]
This has been fixed.
