### ISSUE TITLE
(#78b) Delivery Updates Before Acks/Txns, causing external syncing issue

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#35]
This is a likely cause of the Pharmaserv team's issue with getting null values in the acknowledged field after syncing a completed delivery, due to the possible scenario of syncing the delivery before the app has sent the ack updates.

**Comment by jasonmadrid** [comment]
@RyanNerd @pablo57 This helps resolve a syncing issue.  The iOS app submits the delivery and then the acknowledgements and transactions.  So a sync can occur in between and cause a bad state.  Updated/inserted acknowledgements and transactions need to propagate a sync_stamp update to the owning delivery record.

**Comment by jasonmadrid** [comment]
hook test

**Comment by jasonmadrid** [comment]
hook test 2

**Comment by jasonmadrid** [comment]
hook test 3

**Comment by jasonmadrid** [comment]
hook test 4

**Comment by jasonmadrid** [comment]
@RyanNerd @pablo57 This helps resolve a syncing issue.  The iOS app submits the delivery and then the acknowledgements and transactions.  So a sync can occur in between and cause a bad state.  Updated/inserted acknowledgements and transactions need to propagate a sync_stamp update to the owning delivery record.

Does that resolve the question?

**Comment by RyanNerd** [comment]
Will use the Symphony Event Dispatch system.

**Comment by brprashanth** [comment]
This has been fixed now.
