### ISSUE TITLE
(#78) null in Acknowledgment.Acknowledged

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#39]
Acknowledgements are still showing null for acknowledged after delivery completed.  Likely related to iPad sync order.

**Comment by jjamminjim** [comment]
Not a bug

**Comment by brprashanth** [comment]
As discussed in the morning, this is occurring on the Bulk Get Deliveries Response. If we an individual delivery is queried, this property is being returned correctly.

**Comment by brprashanth** [comment]
Related to #64
