### ISSUE TITLE
#73 An item can be delivered without the customer signing on the PAD.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#48]
Delivering without the customer signing. 
“Delivery Signature” is marked mandatory  - Driver can just make a delivery without getting the signature of the customer.

**Note** that signature_required attribute was marked to True.
The customer can click Agree without signing on the designated area.

See below screenshot for steps.
![no signatures](https://cloud.githubusercontent.com/assets/8714134/21695933/2e133034-d362-11e6-824f-22e0c9c6bde9.png)

**Comment by jjamminjim** [comment]
Fixed!

**Comment by brprashanth** [comment]
This seems to be working. We have validated this. Please remove the **needs_verification** tag
We will let you know if in case we find any other issue regarding to the same.
