### ISSUE TITLE
#67 Bulk patch requests are failing if any one record is found to be invalid/archived/not found

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#49]
When testing for batch priority patch requests, we found that the whole request fails if a record is archived/or had an issue. 
In the example below, external id – 11017A9 was not present/archived.

To bail out from this error situation, we expect RxTrax to handle the bulk record updates this way:

1.	RxTrax tries to attempt to patch all requested records.
2.	Handling error Record(s): If one or more records are failing/missing RxTrax should provide details about the missing records
For example:
Instead of just “record not found”, we are expecting “record <<external id>> is not found”
3.	Handling good Records(s): RxTrax will go ahead and update all the other records that it can update. 

In the example (see screenshots), record 11017A9 is not present in rxtrax so the complete request failed with an error saying “Record not found”. 
In this case if a record is not found the bulk priority patch request should continue without any errors and return back the delivery ids which had errors in it.

![ipad](https://cloud.githubusercontent.com/assets/8714134/21698230/5686ca9e-d36c-11e6-9631-c44f0e0e4221.png)

**Comment by jasonmadrid** [comment]
The API now processes bulk POST/PATCH requests as documented here: http://docs.rxtrax.apiary.io/#introduction/submitting-multiple-records

**Comment by brprashanth** [comment]
This has been fixed.
