### ISSUE TITLE
(#3c) Implement Cancelled Delivery Status in UI

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#5]

**Comment by pablo57** [comment]
![image](https://cloud.githubusercontent.com/assets/9058749/21993830/0d408d86-dbda-11e6-88bd-1381f82237d3.png)

![image](https://cloud.githubusercontent.com/assets/9058749/21993841/1db7a708-dbda-11e6-9a37-019742cdf57d.png)

![image](https://cloud.githubusercontent.com/assets/9058749/21838493/1f053b36-d787-11e6-80c1-6f757c3c3eff.png)

**Comment by pablo57** [comment]
The user interface has been updated to implement cancelled delivery status. I have provided some images.

**Comment by brprashanth** [comment]
Hi @pablo57 
Does this mean that an item can be cancelled only via the Web UI. Will there by any UI from the IPAD as well?

**Comment by jasonmadrid** [comment]
@brprashanth This only implements visible status for cancelled items in the UI.  There will also soon be UI for actually cancelling an item, on both web and mobile.

**Comment by jasonmadrid** [comment]
However @pablo57, I don't believe this is deployed yet.  Please reopen if that's true.

**Comment by pablo57** [comment]
@brprashanth as stated by @jasonmadrid, this is only for displaying the status of cancelled deliveries. 

Sorry, this has not been deployed yet. Will reopen for now until it has been deployed.
