### ISSUE TITLE
(#95) Gift Card Balance and Prepaid Card Balances are not being displayed on the Receipts on the IPAD.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#53]
Gift Card Balance and Prepaid Card Balances are not being displayed on the Receipts on the IPAD.
The Gift Card balance should be indicated as per the below example
    Gift Card #:   XXXXXXXXXXXX1234
    Auth #: 984329894
    Amount              : $13.00
    Remaining Balance   : $45.00

The card balance is found under TransactionResult under AdditionalParameters under Amount Details

```
<TransactionResult>
   .....
   .....
  <AdditionalParameters>
    <SignatureData />
    <AmountDetails>
      .....
      .....
      <RemainingCardBalance>27.40</RemainingCardBalance>
      .....
      .....
    </AmountDetails>
  </AdditionalParameters>
</TransactionResult>

```
![gift card receipt](https://cloud.githubusercontent.com/assets/8714134/21781909/d23d699a-d687-11e6-854a-92881d77a564.png)

Sample Gift Card Responses:

[GIFT Full Approval with No Remaining Card Balance.txt](https://github.com/rxtrax/tracking/files/694562/GIFT.Full.Approval.with.No.Remaining.Card.Balance.txt)
[GIFT Full Approval with Remaining Card Balance.txt](https://github.com/rxtrax/tracking/files/694561/GIFT.Full.Approval.with.Remaining.Card.Balance.txt)

![gift card no balance](https://cloud.githubusercontent.com/assets/8714134/21782288/428629ac-d689-11e6-93a6-db18c7e4dae7.PNG)

**Comment by jjamminjim** [comment]
https://github.com/rxtrax/rws-vendor-api/tree/master/_cayan

**Comment by brprashanth** [comment]
The issue is fixed now.

**Comment by brprashanth** [comment]
Test with the 4.1.0 (0.34.0) and found that the remaining card balance is getting displayed for all credit card transactions.

Note: as explained above, it should only display for Gift Cards, and for Credit Cards that has incoming responses - **The Remaining Card Balance property greater than 0**

```
<TransactionResult>
   .....
   .....
  <AdditionalParameters>
    <SignatureData />
    <AmountDetails>
      .....
      .....
      <RemainingCardBalance>27.40</RemainingCardBalance>
      .....
      .....
    </AmountDetails>
  </AdditionalParameters>
</TransactionResult>

```
