### ISSUE TITLE
(#96) The Receipts are not printed as per the EMV Card Certification Requirement

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#54]
The Receipts are not printed as per the EMV Card Certification Requirement.

The Receipts should be printed based on the EMV Card Brand Certification Requirement.
Please refer the attached sheet and the Receipt example documentation for more info.
Please refer the various card responses attached.

*Few examples* (Refer the excel sheet & documentation for more info).
1. All Card brands - Must Include AID *available under EMV node in Transaction Response*
2. VISA & Master Card - Do not print (include) expiry date
3. Amex - Print (include) expiry date
4. PIN Statement - Must include for all card brands (if available). *available under EMV node in Transaction Response*

[EMVReqbyCardBrand(7-7-2015).xlsx](https://github.com/rxtrax/tracking/files/694617/EMVReqbyCardBrand.7-7-2015.xlsx)

[PSv POS Receipt Examples.docx](https://github.com/rxtrax/tracking/files/694620/PSv.POS.Receipt.Examples.docx)

[All Card Sample Respones.zip](https://github.com/rxtrax/tracking/files/694621/All.Card.Sample.Respones.zip)

![health card - visa mc](https://cloud.githubusercontent.com/assets/8714134/21782994/d16a6d52-d68b-11e6-80ec-3e61a228a24b.PNG)
![visa debit](https://cloud.githubusercontent.com/assets/8714134/21782995/d18dea16-d68b-11e6-8177-e76f79f16619.PNG)
![amex](https://cloud.githubusercontent.com/assets/8714134/21782996/d1a4aa30-d68b-11e6-867b-c53da61900ce.PNG)
![diners club](https://cloud.githubusercontent.com/assets/8714134/21782997/d1a5d0ea-d68b-11e6-9bbb-3f46bc77edd4.PNG)

**Comment by jjamminjim** [comment]
https://github.com/rxtrax/rws-vendor-api/tree/master/_cayan

**Comment by brprashanth** [comment]
This has been fixed. Except the EMV Decline receipts, the receipts are working.
