### ISSUE TITLE
(#98) When the RxTrax app cannot find the Genius Wireless Device, it take a long time (it actually timesout) to respond.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#56]
When the RxTrax app cannot find the Genius Wireless Device, it take a long time (it actually timeout) to respond.

**To Improve the User Experience**, 
1. Instead of relying on the timeout, the IPAD can send a ping call to the device to check if it is online/active. In most cases, when the IPAD cannot find the device, it timesout after 120 seconds or more and the user has to wait until that happens.
2. We can provide for the user to click and enter the IP Address. Currently, it only prompts when it times out.

![1 - checking - takes long time if device is not available](https://cloud.githubusercontent.com/assets/8714134/21785842/9a70fada-d697-11e6-9c7a-abad758417be.PNG)
![2 - after timeout](https://cloud.githubusercontent.com/assets/8714134/21785845/9bbd1482-d697-11e6-897d-571cf3de3707.PNG)
![3 - when connected](https://cloud.githubusercontent.com/assets/8714134/21785846/9ddcb2e0-d697-11e6-98a7-94ea308eb97b.PNG)

**Comment by jjamminjim** [comment]
Try to do a better 'ping'. This ping still passes too liberally, so I also decreased timeout to 15 seconds.

**Comment by brprashanth** [comment]
The issue is fixed now.
