### ISSUE TITLE
(#103) The Acknowledged Property under the "Acknowledgement" node in the Get Deliveries call is showing up as null even though when the customer has agreed (yes/no) on the radio buttons.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#64]
(#103) The Acknowledged Property under the "Acknowledgement" node in the Get Deliveries call is showing up as null even though when the customer has agreed (yes/no) on the radio buttons.

*The Acknowledged fields are coming back as null on the bulk get deliveries request. (refer response.txt)*
[response.txt](https://github.com/rxtrax/tracking/files/699730/response.txt)

![null acknowledgements](https://cloud.githubusercontent.com/assets/8714134/21861224/4da08bd4-d80a-11e6-8cd1-a01ad8265c8a.png)

*Tested again Today and observed this on Individual Request:*
We can see that we are getting all the data related to ack messages correctly when we retrieve it using the external id. The same ack messages should be displayed if we retrieve the information using bulk sync url.
Refer Request_Data31012.txt, ResponseData31012Bulk.txt, ResponseSingleAck31012.txt*
[Request_Data31012.txt](https://github.com/rxtrax/tracking/files/702406/Request_Data31012.txt)
[ResponseData31012Bulk.txt](https://github.com/rxtrax/tracking/files/702407/ResponseData31012Bulk.txt)
[ResponseSingleAck31012.txt](https://github.com/rxtrax/tracking/files/702408/ResponseSingleAck31012.txt)

**Comment by brprashanth** [comment]
This issue is occuring on the bulk get deliveries request. If you individually query a delivery, the acks are coming back. Refer the test findings and attachments.

**Comment by brprashanth** [comment]
The issue is still re-occuring. The Acknowledged property is returning null especially when the customer name is different from the delivery recipient name.

**If the customer name and the delivery recipient name is different **,  we are getting the acknowledgment flags as null. For Ex : We have an RX of customer A and we have mentioned to deliver the same Customer A Rx to Customer B, Then we won’t be getting the acknowledgment flags. 

However, when both the customer and Recipient name is same then the acknowledgement flags are coming as expected.

**Comment by jasonmadrid** [comment]
@brprashanth Do you have an external_id for a delivery with this problem?

**Comment by brprashanth** [comment]
[response.txt](https://github.com/rxtrax/tracking/files/709381/response.txt)

Please find the attached response from our tests today. Please see the acknowledged property it is reporting null.

**Comment by jasonmadrid** [comment]
OK, we've done extensive testing on the latest builds and are not experiencing the issue.

If this is still being experienced, I will need to get on a call with @brprashanth and have the issue demonstrated.

**Comment by brprashanth** [comment]
Reopening this issue as we are seeing few scenarios that are not working

**When Customer and Recipient are Different**
[Customer and Reciepient Different_Request_610209.txt](https://github.com/rxtrax/tracking/files/724407/Customer.and.Reciepient.Different_Request_610209.txt)
[Customer and Reciepient Different_Response_610209.txt](https://github.com/rxtrax/tracking/files/724408/Customer.and.Reciepient.Different_Response_610209.txt)

**When Customer and Recipient are Same**
[Customer and Reciepient Same_Reponse_610213.txt](https://github.com/rxtrax/tracking/files/724409/Customer.and.Reciepient.Same_Reponse_610213.txt)
[Customer and Reciepient Same_RequestData_610213.txt](https://github.com/rxtrax/tracking/files/724410/Customer.and.Reciepient.Same_RequestData_610213.txt)

**Comment by jasonmadrid** [comment]
Fixes are in and tested in the latest build.  As long as the user answers each acknowledgement, the `acknowledged` field will be `true` or `false`.

If the ack is sent with `required: true`, the user will be forced to answer before the delivery can be completed, and `acknowledged` is guaranteed to be `true` or `false`.

If the ack is sent with `required: false`, the user will not have to answer that ack and `acknowledged` can come back as `null`.

**Comment by brprashanth** [comment]
Reopening this issue:

**Issues Found**:
1. Found that there is a LAG int the IPAD application when it sends the acknowledgement results back to RxTrax servers. 
2. After the delivery is finished and orange icon, turns green. The payment and delivery information is available on the server. However, for upto 5-10 minutes the acknowledgement message selections never get propogated.
3. If the Pharmaserv tries to to perform a sync, it gets all the information except the acknowledgement results - acknowledged or not.

Example:
External ID: "98122"
The response received immediately after 5 minutes: Observe the acknowledged property is null.
[103 acknowledged null.txt](https://github.com/rxtrax/tracking/files/743265/103.acknowledged.null.txt)

This happens inconsistently, sometimes it sends, sometimes not.

**Comment by jasonmadrid** [comment]
We have fixed this with sync order/transaction changes in the latest iOS build.

**Comment by brprashanth** [comment]
The issue seem to be fixed.

**Comment by brprashanth** [comment]
This is failing on the build 4.0.0 (0.25.0) and thus reopening.

**Comment by brprashanth** [comment]
This has been fixed.
