### ISSUE TITLE
(#105) Deliveries that are 'sent back' is not indicated that it is sent back in the get deliveries response.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#66]
If a delivery is 'sent back', we are not receiving any data that indicates it is sent back. 
1. The reschedule flag also is not true. 
2. Also when we reschedule and change the delivery after time, we are not receiving reschedule flag as true.

Jim mentioned in the call today that this dialog will be designed to incorporate the delivery before time and will be redone to handle the "Sent Back" status or "Rescheduled time (before/after)"

**Comment by jasonmadrid** [comment]
Verified that when 'Send Back' is used on mobile, the `rescheduled` flag is set to `true`, and the `status` field returned by the API is `reschedule`.

**Comment by brprashanth** [comment]
The issue is fixed. Removing the needs_verification label.
