### ISSUE TITLE
(#108) When a credit card is declined/failed the RxTrax receipt is showing the declined transaction on the receipt.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#69]
When a credit card is declined/failed the RxTrax receipt is showing the declined transaction on the receipt.

Please do not include the declined/failed transactions in the incoming response/receipt.
Currently,
1. The receipts are showing declined/failed responses
2. The incoming transaction responses also contains decline/failed response. 

![declines on receipt png](https://cloud.githubusercontent.com/assets/8714134/21945439/a21632ec-d9b1-11e6-9934-4311a658069d.jpeg)

**Comment by brprashanth** [comment]
Thanks Jim. This has been fixed on the IPAD now. 
The IPAD is not reporting any failed, user cancelled, declined card responses on the receipt. 

However, the API is still returning all failed, declined, user cancelled responses. The API should not return all failed, user cancelled, declined, communication errors responses that occured while performing a card transaction.  

![failed external id 31024 record 05](https://cloud.githubusercontent.com/assets/8714134/21997953/82b91848-dc08-11e6-8f3e-bb39e3d6165a.png)
![failed external id 61079 record 02](https://cloud.githubusercontent.com/assets/8714134/21997954/82cce418-dc08-11e6-8a96-b2700dc29da2.png)
[Response - failed card transactions.txt](https://github.com/rxtrax/tracking/files/709335/Response.-.failed.card.transactions.txt)

**Comment by jjamminjim** [comment]
@jasonmadrid we should discuss this when you are available.

**Comment by jasonmadrid** [comment]
Cancelled transactions are no longer returned in delivery GET results.
