### ISSUE TITLE
(#109) IPAD- The customer instructions are being cut off. (Cropped). This happens when there is an additional override address and instruction.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#70]
(#109) IPAD- The customer instructions are being cut off. (Cropped). This happens when there is an additional override address and instruction.

1. The entire instruction line should be displayed. Should not be cropped.
2. The "Delivery To" is coming up in additional intermittently. 

![cut off screen](https://cloud.githubusercontent.com/assets/8714134/21945673/e94a49c2-d9b2-11e6-95ff-753d0e951f74.jpg)

![5](https://cloud.githubusercontent.com/assets/8714134/21945686/f82bfdf0-d9b2-11e6-89fa-5eb2fafd008f.PNG)

**Comment by jjamminjim** [comment]
This is not a bug. These text fields are in scroll views and the driver can click and scroll the text.

**Comment by brprashanth** [comment]
Hi Jim,
There are couple of things in this issue:
1.  The "Delivery To" header on top appears intermittently when we have override address (see screenshots). It will be better if we can display the "Delivery To" text always when an override address is present.
2. Also, clearer indication for "Scroll" should be provided.
