### ISSUE TITLE
(#110) Issuing "User Cancel" on the IPAD by clicking the "CANCEL" button on the Collect Payment window is not cancelling the transaction on the genius wireless device. 

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#72]
(#110) Issuing "User Cancel" on the IPAD by clicking the "CANCEL" button on the Collect Payment window is not cancelling the transaction on the genius wireless device. 

Upon clicking of the "Cancel" button, the application closes the dialog and stops monitoring the genius device. However, on the wireless device, the transaction is still left initiated.
Unknowingly a customer might end up swiping the card on the wireless device, but the IPAD will not receive the payments.

![step 1 before initiate](https://cloud.githubusercontent.com/assets/8714134/21999724/e0168af8-dc11-11e6-8ba9-4e01dae6b821.JPG)
![step 2 before connect device](https://cloud.githubusercontent.com/assets/8714134/21999727/e17eec28-dc11-11e6-9563-0d46443fe2af.JPG)
![step 3 initiated payment](https://cloud.githubusercontent.com/assets/8714134/21999728/e2f311ba-dc11-11e6-9c56-4fe102d32582.JPG)
![step 4 user clicked cancel on the ipad](https://cloud.githubusercontent.com/assets/8714134/21999731/e51d2d72-dc11-11e6-964f-12825e65e716.JPG)
![step 5 the device is left in the initiated state](https://cloud.githubusercontent.com/assets/8714134/21999734/e8cc4afc-dc11-11e6-98b4-fc7b4acb8417.JPG)

**Comment by jjamminjim** [comment]
I now disable `Cancel` button when processing a credit card.
