### ISSUE TITLE
(#112) RxTrax - The standard delivery message on the first screen of RXtrax does not need the work Prescription in it. It should say "items" we have the 4 specific RX questions coming up if there is an RX in the transactions.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#74]
RxTrax - The standard delivery message on the first screen of RXtrax does not need the work Prescription in it. It should say "items" we have the 4 specific RX questions coming up (acknowledgments & Hipaa) if there is an RX in the transactions.

![image](https://cloud.githubusercontent.com/assets/8714134/22046725/045a2176-dcf9-11e6-8e36-8ba2550032d9.png)

**Comment by jjamminjim** [comment]
@brprashanth This is the default message that we display for our current pharmacy clients.  The default can be customized however.  If you would like a custom message for McKesson pharmacies you can set the `recipient_acknowledgement_label` item on the `Pharmacy`
