### ISSUE TITLE
Message sent from Enterprise Rx is not reaching RxTrax 

### ISSUE THREAD

**Issue by sindhujan-sid** [rxtrax/tracking#75]

**Comment by sindhujan-sid** [comment]
Steps to Repeat:

 1) Process an Rx with 'Mobile delivery RxTrax' as delivery option till Verification Screen.
 2) Select 'Approve and Follow' in the verification screen. 
 3) The 'Mobile delivery options' window is displayed > Select a Route(If no routes - General) ,Check the Populate patient address from patient profile check Box > Select 'Ok' button
 4) Rx is processed to 'Release to patient screen' > A record is created for the Rx in the above setup in the DB 
 5) Run the Batch for transmitting the data from ERx to RxTrax 
Actual Result: The Status of the record  in the above steps is changed to 'R'(Information not sent)

Expected Result: The status of the record should be updated to 'I' (Information sent to RxTrax.)

The Response code  : Response code 400 returned.

JSON  response: 
{  
   "external_id":"cps-ERX-NDCQ34-null-deliveries-10292012014&23213801",
   "delivery_date":1484611200,
   "deliver_before":1484690460,
   "instructions":"SADSADASDASDSADSA",
   "address1":"350 SUNSET DR",
   "city":"PITTSBURGH",
   "state":"PA",
   "postal_code":"15228",
   "collect_amount":0.0,
   "photo_id_required":true,
   "signature_required":true,
   "recipient_photo_required":true,
   "payment_required":true,
   "cancelled_on":null,
   "recipient":{  
      "external_id":"cps-ERX-NDCQ34-null-patient-23213801",
      "first_name":"A",
      "last_name":"A",
      "home_phone":"1111111111",
      "address1":"350 SUNSET DR",
      "city":"PITTSBURGH",
      "state":"PA",
      "postal_code":"15228",
      "country":"USA",
      "facility":false,
      "is_archived":false
   },
   "external_route_id":"587ed64b1717d",
   "delivery_prescriptions":[  
      {  
         "external_id":"cps-ERX-NDCQ34-null-delivery_prescriptions-10163098016",
         "quantity":"30.0",
         "fill_number":0,
         "partial_fill_sequence":0,
         "prescription":{  
            "external_id":"cps-ERX-NDCQ34-null-prescription-10163098016",
            "rx_number":"004093",
            "description":"HUMIRA 10MG/0.2ML PSKT",
            "customer":{  
               "external_id":"cps-ERX-NDCQ34-null-patient-23213801",
               "first_name":"A",
               "last_name":"A",
               "home_phone":"1111111111",
               "address1":"350 SUNSET DR",
               "city":"PITTSBURGH",
               "state":"PA",
               "postal_code":"15228",
               "country":"USA",
               "facility":false,
               "is_archived":false
            },
            "is_archived":false
         },
         "is_archived":false
      }
   ],
   "acknowledgements":[  
      {  
         "external_id":"cps-ERX-NDCQ34-null-acknowledgements-RX_ACK",
         "text":"I am receiving all Rx's.",
         "is_archived":false
      },
      {  
         "external_id":"cps-ERX-NDCQ34-null-acknowledgements-EASY_CAP_ACK",
         "text":"I authorize easy open caps.",
         "is_archived":false
      }
   ],
   "is_archived":false
}

Tech response: 
->{"success":false,"code":40    0,"data":null,"message":"Invalid request.  Check missing parameters section of response.","missing":{"optional":{"original_delivery_date":"datetime","deliver_after":"time","cancelle    d_on":"datetime","en_route":"boolean","collect_info":"json","route":"Route","recipient.mobile_phone":"string","recipient.email":"string","recipient.address2":"string","recipient.fac    ility_name":"string","recipient.notes":"string","external_recipient_id":"external_reference","acknowledgement_ids":"array[string]","prescriptions":"array[Prescription]","delivery_pr    escriptions[0].unit_price":"float","delivery_prescriptions[0].total_price":"float","delivery_prescriptions[0].prescription.is_misc":"boolean","delivery_prescriptions[0].prescription    .customer.mobile_phone":"string","delivery_prescriptions[0].prescription.customer.email":"string","delivery_prescriptions[0].prescription.customer.address2":"string","delivery_presc    riptions[0].prescription.customer.facility_name":"string","delivery_prescriptions[0].prescription.customer.notes":"string","delivery_prescriptions[0].prescription.external_customer_    id":"external_reference","delivery_prescriptions[0].external_prescription_id":"external_reference","delivery_prescriptions[0].customer":"Customer","delivery_prescriptions[0

**Comment by sindhujan-sid** [comment]
@jasonmadrid  Please look into this issue

**Comment by gopiraj24** [comment]
@sindhujan-sid  There seem to be an issue with the the request . Hence closing this issue.
