### ISSUE TITLE
Route infromation is sent to RxTrax from Enterprise Rx but we get an error (route unavilable) 

### ISSUE THREAD

**Issue by sindhujan-sid** [rxtrax/tracking#76]
The delivery details transmitting from Enterprise Rx to RxTrax is failing with response code '400'.

Request

{"external_id":"cps-ERX-UNKNOWN-ERX-deliveries-10004458801&1892810","delivery_date":1484697600,"collect_amount":0.0,"cancelled_on":1484693548,"route":{"external_id":"General_1","name":"General","sunday":true,"monday":true,"tuesday":true,"wednesday":true,"thursday":true,"friday":true,"saturday":true,"is_default":true,"is_archived":false},"delivery_prescriptions":[{"external_id":"cps-ERX-UNKNOWN-ERX-delivery_prescriptions-10005497001","fill_number":0,"partial_fill_sequence":0,"prescription":{"external_id":"cps-ERX-UNKNOWN-ERX-prescription-10005497001","rx_number":"6000162","external_customer_id":"cps-ERX-UNKNOWN-ERX-patient-1892810","is_archived":true},"is_archived":true}],"external_recipient_id":"cps-ERX-UNKNOWN-ERX-patient-1892810","is_archived":false}

Response 

{"success":false,"code":400,"data":null,"message":"Invalid request.  Check missing parameters section of response.","missing":{"optional":{"instructions":"string","original_delivery_date":"datetime","deliver_before":"time","deliver_after":"time","address1":"string","city":"string","state":"string","postal_code":"string","photo_id_required":"boolean","signature_required":"boolean","recipient_photo_required":"boolean","payment_required":"boolean","en_route":"boolean","collect_info":"json","route.driver":"User","route.external_driver_id":"external_reference","external_route_id":"external_reference","recipient":"Customer","acknowledgements":"array[Acknowledgement]","acknowledgement_ids":"array[string]","prescriptions":"array[Prescription]","delivery_prescriptions[0].quantity":"int","delivery_prescriptions[0].unit_price":"float","delivery_prescriptions[0].total_price":"float","delivery_prescriptions[0].prescription.description":"string","delivery_prescriptions[0].prescription.is_misc":"boolean","delivery_prescriptions[0].prescription.customer":"Customer","delivery_prescriptions[0].external_prescription_id":"external_reference","delivery_prescriptions[0].customer":"Customer","delivery_prescriptions[0].external_customer_id":"external_reference"},"required":{"delivery.external_route_id=>external_route_id":"route_available"},"invalid":{"delivery.external_route_id=>delivery_date":"route_available"}}}

**Comment by sindhujan-sid** [comment]
@jasonmadrid  Please look into this issue

**Comment by jasonmadrid** [comment]
A fix has been deployed.  Please verify.
