### ISSUE TITLE
#115 Acknowledgement Messages still show up after deleted Rx(s). 

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#77]
This is related with issue #59 - Update Delivery Prescription does not work if Prescriptions are Removed

A post a delivery with Rx(s) - The acknowledgment messages needed to be displayed or posted.
Now, the pharmacist deletes the Rx(s). 
POS is sending the updated request with the deleted Rx(s) and also sending "null" as Acknowledgments - as there may be no acknowledgment(s) to be displayed  or all-together new messages needs to be displayed.

This is not getting refreshed. 
Currently, the Acknowledgement messages is completely ignored after a delivery is being posted. 
Please note that any updates made to Acknowledgement to be reflected.

[initialrequestdata.txt](https://github.com/rxtrax/tracking/files/714188/initialrequestdata.txt)
[UpdatedRequestData.txt](https://github.com/rxtrax/tracking/files/714189/UpdatedRequestData.txt)

**Comment by jasonmadrid** [comment]
Updating a delivery with a new list of delivery-prescriptions now replaces what was there before. null can now be passed to clear the delivery of any items. This all works now with acknowledgements also. I believe this new behavior resolves this issue.

**Comment by brprashanth** [comment]
The issue seems to be not working. Will share the scenarios shortly.

**Comment by brprashanth** [comment]
Please find the request and response json when it is failing:

[RequestJson.txt](https://github.com/rxtrax/tracking/files/724425/RequestJson.txt)
[ResponseJson.txt](https://github.com/rxtrax/tracking/files/724426/ResponseJson.txt)

![img_20170123_162230](https://cloud.githubusercontent.com/assets/8714134/22214573/6ae94ad8-e16e-11e6-9d00-cff35ea9c30d.jpg)
![img_20170123_162243](https://cloud.githubusercontent.com/assets/8714134/22214572/6ae5dede-e16e-11e6-9883-69819a19f544.jpg)

**Comment by jasonmadrid** [comment]
Fixed in the API and on mobile.
