### ISSUE TITLE
#113 The receipt in IPAD displays description with SKU’s and not item name.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#78]
#113 The receipt in IPAD displays description with SKU’s and not item name.
The Receipt should display Item Description

![item receipt](https://cloud.githubusercontent.com/assets/8714134/22069518/1e6d9b9e-dd6f-11e6-914b-b5fb06caabea.jpg)

**Comment by jjamminjim** [comment]
@brprashanth I understand that it is a bit confusing but the `rx_number` string in the `Prescription` table is what we use as a title/name for misc items.  In fact it is also what is displayed as the title/name for non-misc (prescription) items as well. It would break current functionality (and cause inconsistency between misc and non-misc items) to display `description` in one instance and `rx_number` in another. It would also break the usage pattern of our current userbase.

I wold suggest that you put the SKU number in the `description ` field and the item name/titke in the `rx_number` field for misc items.

**Comment by brprashanth** [comment]
ok Jim. We will discuss internally get back if needed. Thanks.

**Comment by brprashanth** [comment]
This is closed.
