### ISSUE TITLE
(#116) HIPAA - The mandatory questions should be answered with either 'Yes' or 'No'

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#79]
HIPAA - the mandatory questions should be answered with either 'Yes' or 'No'.
However, currently the mandatory questions only takes a 'Yes'. Currently it is mandatory YES and it won’t let the user leave one of them as the default 'No'.

The following changes are expected:
1. Any one of these questions can technically be answered with a no.
2. Also, the corresponding user's selection should be propagated back to us in the API.

**Comment by jjamminjim** [comment]
So what then does `mandatory` mean?

**Comment by brprashanth** [comment]
The user should still be able to complete by clicking 'No'.  Right now, it forces you to say 'Yes' all the time.
