### ISSUE TITLE
Issue with Default Routes - EnterpriseRx

### ISSUE THREAD

**Issue by LakshmipriyaThangamuthu** [rxtrax/tracking#83]
Whenever a Request is sent from ERx to RxTrax via a Default Route  - An Error Code 500 is Returned

**REQUEST**
{"external_id":"cps-ERX-NDCD01-ERX-deliveries-10007974601&4612200","delivery_date":1485043200,"collect_amount":0.0,"cancelled_on":1484902767,"delivery_prescriptions":[{"external_id":"cps-ERX-NDCD01-ERX-delivery_prescriptions-10008376401","fill_number":0,"partial_fill_sequence":0,"prescription":{"external_id":"cps-ERX-NDCD01-ERX-prescription-10008376401","rx_number":"002761","external_customer_id":"cps-ERX-NDCD01-ERX-patient-4612200","is_archived":true},"is_archived":true}],"external_recipient_id":"cps-ERX-NDCD01-ERX-patient-4612200","is_archived":false}

**RESPONSE**
|MSG:Non-2xx response received->500 response->{"suc                                                                                   cess":false,"authorized":false,"code":500,"data":{"error_instance":"588217e454e1                                                                                   3244361250"},"message":"Unknown error.  Rx Trax developers have been notified."}

**Comment by LakshmipriyaThangamuthu** [comment]
Hi @jasonmadrid  

we tried passing a Message to RxTrx from ERx using the Default Route after issue 76 was CLOSED.
But it FAILED with the ERROR CODE : 500

Please have a look into the issue.

Thanks,
Lakshmipriya

**Comment by jasonmadrid** [comment]
This is fixed via a workaround on our side for now.  There is a bug we need to fix.  In the meantime, be careful not to change the is_default flag on routes.
