### ISSUE TITLE
Cosmetic -  Issue with the Calendar Date displayed with the Dashboard Items

### ISSUE THREAD

**Issue by LakshmipriyaThangamuthu** [rxtrax/tracking#85]
![dashboard_1](https://cloud.githubusercontent.com/assets/25032786/22154697/873b0578-df52-11e6-82da-265edff2f011.JPG)
![dashboard_2](https://cloud.githubusercontent.com/assets/25032786/22154699/899faeb8-df52-11e6-8667-ddc5105d7a82.JPG)

The calendar date getting Displayed on the top is always the date of the middle item [middle Item with in the 3 Items ] getting Displayed in the Dashboard

**Comment by LakshmipriyaThangamuthu** [comment]
Hi @jasonmadrid 

Please have a look into this issue.

Thanks

**Comment by jasonmadrid** [comment]
Fixed.  Though you may need to clear your browser cache to see the changes.
