### ISSUE TITLE
(#8) Single Screen Acknowledgements & Signature

### ISSUE THREAD

**Issue by jasonmadrid** [rxtrax/tracking#9]
Instead of the one ack per screen currently implemented.

**Comment by brprashanth** [comment]
As discussed in the call this morning, please find the mock up screens on how our Hippa Messages/Acknowledgement messages needs to be displayed. Currently each of the messages are getting displayed in separate screens.
Please let me know if you have any other questions.

Mockup #1: The following window that appears after selecting AGREE and will have the below new fields if all of the Signature Types from Signature Preferences window are selected
The POS Requests ALL HIPAA messages:
 
![ack1](https://cloud.githubusercontent.com/assets/8714134/21705844/dce015c4-d398-11e6-901b-f61b7de832bb.png)


Mockup #2: The following window that appears after selecting AGREE and will have the below new fields if all of the Signature Types from Signature Preferences window are selected except for Privacy Signature type (not selected)
The POS Requests Counseling, Easy Open Caps, Rx Acks:
 
![ack2](https://cloud.githubusercontent.com/assets/8714134/21705847/dff1c488-d398-11e6-9bf9-1f9b419ccde2.png)

Mockup 4: The following window that appears after selecting AGREE and will have the below new fields if none of the Signature Types from Signature Preferences window are selected 
The POS Requests None:

![ack3](https://cloud.githubusercontent.com/assets/8714134/21705854/eb2af996-d398-11e6-91fb-3532db9a8c00.png)

**Comment by jjamminjim** [comment]
Fixed

**Comment by brprashanth** [comment]
This has been fixed now.
