### ISSUE TITLE
Random Issue - Some times Cancelled on Delivered on Fields are Getting Overlapped 

### ISSUE THREAD

**Issue by LakshmipriyaThangamuthu** [rxtrax/tracking#90]
In the Rx Sandbox [In IPAD] Delivered On & cancelled On are getting overlapped

![canceleld_on_delivery_on](https://cloud.githubusercontent.com/assets/25032786/22212274/0e01c500-e1b6-11e6-8888-317b47c77148.png)

**Comment by brprashanth** [comment]
Hi Lakshmipriya - just a thought. 
Please check if you have set both cancelled on and deliver after fields?? This could be a data issue.
