### ISSUE TITLE
(#125) RxTrax App Crashed while Viewing the Collect Payment window for Credit Card Payments

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#93]
RxTrax App Crashed while Viewing the Collect Payment window for Credit Card Payments 

**External Id : 8912237**

This was three card transaction.
****0176 (Visa)                       EMV Contact          $61.80
****4579 (Visa)                       Swiped                    $61.50
****2513 (American Express)                 EMV Contact          $5.00

Completed the payments on the Collect Payment windows and returned to main screen.
Clicked on “Collect” button again to view the collected payments.
The application crashed immediately.

Since then, I’m not able to go to collect payment window for this Customer (Veronica Tailor). 

**Three issues observed here** :
1.	It crashed out while viewing the collect payment window. 
2.	It is not remembering the previously paid transactions. 
3.	It is not letting the driver to collect payment and complete the transaction again. Each time I return to collect payment, it keeps crashing for this customer External Id : 8912237
4.     In real time this will be a challenge to explain the customer especially when the money is collected, but the app is not letting you complete the transaction and it has lost the payments made.

![payments collected](https://cloud.githubusercontent.com/assets/8714134/22226966/19d18080-e19f-11e6-9dc2-a01bb28754ce.png)
![img_53012](https://cloud.githubusercontent.com/assets/8714134/22226967/1ad62d3c-e19f-11e6-9673-1b3c519e26f7.png)

**Comment by jjamminjim** [comment]
@brprashanth Which version of the app are you running?

**Comment by brprashanth** [comment]
The latest. I just installed this morning.

**Comment by jjamminjim** [comment]
It looks like a transaction of $0.00 was allowed to pass through, that Genius ignored and approved with no transaction data. This caused an exception, when we tried to parse through the existing transactions. 
I have fixed both the exception and the payment dialog to not allow $0.00 transactions.
