### ISSUE TITLE
RxTrax not displaying the Rx number for Multi item order when one Rx is cancelled and other Rx is ready for delivery in Enterprise Rx application

### ISSUE THREAD

**Issue by sindhujan-sid** [rxtrax/tracking#94]
**Summary :** RxTrax  is not displaying the Rx number for Multiple item order when one Rx is cancelled and other is ready for delivery. 
**Expected Result :** When one Rx is cancelled , The Rx which is ready for delivery should be displayed in the RxTrax application. 
**Actual Result :** Currently both the Rx numbers are deleted or cleared from RxTrax application when one Rx is cancelled in a order.

**Cancel request:** 
{"external_id":"cps-ERX-NDCQ14-YUC-deliveries-10105193016&6916615","delivery_date":1485648000,"collect_amount":87931.42,"cancelled_on":null,"external_route_id":"5886fee495cd9","delivery_prescriptions":[{"external_id":"cps-ERX-NDCQ14-YUC-delivery_prescriptions-10071038420","fill_number":0,"partial_fill_sequence":0,"prescription":{"external_id":"cps-ERX-NDCQ14-YUC-prescription-10071038420","rx_number":"004170","external_customer_id":"cps-ERX-NDCQ14-YUC-patient-6916615","is_archived":true},"is_archived":true}],"external_recipient_id":"cps-ERX-NDCQ14-YUC-patient-6916615","is_archived":false}

**NOTE: The delivery had 2 Rx's.**

**The Below Screen shot the number of Rxs is displayed as '2' for the record at 4.36 am.**
![rxtrax sandbox - before cancel](https://cloud.githubusercontent.com/assets/25191682/22243983/bcd2420a-e24f-11e6-97f6-7cf8ca3ff9cd.PNG)
**The Below Screen shot both the Rx numbers in Multi order is displayed for the record at 4.36 am.**
![rx details in rxtrax sandbox](https://cloud.githubusercontent.com/assets/25191682/22243982/bcd1949a-e24f-11e6-96d7-b172223c1333.PNG)

**After one item is cancelled >  The Record for the multi item order (4.36 am) is displaying the number of Rxs as '0'.**

![rxtrax sandbox after cancel](https://cloud.githubusercontent.com/assets/25191682/22243981/bcd0ca42-e24f-11e6-908c-06e05d6d785d.PNG)

**In the Rx details screen in RxTrax application , Both the Rx numbers are cleared for Multi item record at 4.36am.**
![rx details in rxtrax sandbox - after cancel](https://cloud.githubusercontent.com/assets/25191682/22243984/bcd5ab2a-e24f-11e6-9568-c09bd4caa6c7.PNG)

But in the dashboard , The details displayed for Jan,29 2017 is displayed correctly.
![dashboard](https://cloud.githubusercontent.com/assets/25191682/22244598/34e3e0d0-e252-11e6-8371-78df29c255a6.PNG)

**Comment by sindhujan-sid** [comment]
@jasonmadrid  Please look into the above issue.

**Comment by sindhujan-sid** [comment]
This was working fine on 1/22/2017 , This might have been broken in latest build.  Only the Rx Count(Rx: ) displayed in customer info is getting displayed as '0' but we are allowed to proceed with  the delivery / Rescheduling of the Rx which is not cancelled from the order.

**Comment by jasonmadrid** [comment]
This is the result of a change in API behavior.  This was requested by the Pharmaserv team.

When making a PATCH request for a delivery, the nested list of delivery-prescriptions provided are now a complete replacement of what was there before.

Given an initial delivery POST with 2 delivery-prescription items:

```
{
	"external_id": "delivery_1",
	"delivery_prescriptions": [
		{
			"external_id": "delivery_prescription_1",
			...
		},
		{
			"external_id": "delivery_prescription_2",
			...
		}
	]
}
```

In order to remove `delivery_prescription_1`, either PATCH and only include the other:

```
{
	"external_id": "delivery_1",
	"delivery_prescriptions": [
		{
			"external_id": "delivery_prescription_2",
			...
		}
	]
}
```

or, include them both, while setting `is_archived` to `true` on the one:

```
{
	"external_id": "delivery_1",
	"delivery_prescriptions": [
		{
			"external_id": "delivery_prescription_1",
			"is_archived": true
			...
		},
		{
			"external_id": "delivery_prescription_2",
			...
		}
	]
}
```
