### ISSUE TITLE
(#126) Minimum iOS Version that should be used for RxTrax to work.

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#95]
This is regarding Minimum iOS Version that should be used for RxTrax to work.

**Observations**:
1.	We had found an odd exception earlier while working with iOS 8.0. 
2.	Today, we were working with a new IPAD that was on iOS 7.x and it was not working. We upgraded it to IOS 10 and now the application is successfully installed.
3.	Currently, the app is working fine mostly with the latest version of iOS 10.x

**Questions**:
1.	What is the Minimum iOS Version that should be used for RxTrax to work?
2.	What if some Pharmacy wants to use their Old IPAD, but for some reason, say
a.	They cannot upgrade their iOS version (hardware limitation)
b.	They don’t want to upgrade their iOS version as they may have another application that runs only on a older version of the iOS.

**Comment by jjamminjim** [comment]
As of version 4.0.0 we support iOS 9 and above. We have dropped iOS versions lower then iOS 9.

**Comment by brprashanth** [comment]
Ok. Thanks Jim. A follow up question on the same:

What is some Pharmacy wants to use their Old IPAD, but for some reason, say
a.	They cannot upgrade their iOS version (hardware limitation)
b.	They don’t want to upgrade their iOS version as they may have another application that runs only on a older version of the iOS.

**Comment by jjamminjim** [comment]
The currently shipping build requires iOS 8 or better.  All devices that can run 8, can run 9, I believe. Anyone that is using the old version of RxTrax should be able to update their devices to (at least) iOS 9.

Here is a list of devices that can run both 8 and 9 ...
iPhone 4S, iPhone 5, iPhone 5S, iPhone 5C, iPhone 6, iPhone 6 Plus
iPad 2, iPad 3. iPad 4, iPad Air, 
iPad Mini, iPad Mini 2
iPod Touch 5G

Here is a list of all devices that support iOS 9...
iPhone 4s, iPhone 5, iPhone 5c, iPhone 5s, iPhone 6, iPhone 6 Plus., iPhone 7, iPhone 7 Plus.
iPad 2, iPad 3, iPad 4, iPad Air, iPad Air 2.
iPad mini, iPad mini 2, iPad mini 3.
iPad Pro 12.9-inch , iPad Pro 9.7-inch
iPod touch (fifth generation) 

Older devices are not supported.

**Comment by brprashanth** [comment]
Thanks Jim for the detailed explanations. That helps.
