### ISSUE TITLE
(#127) Minor corrections required on RxTrax Receipt. 

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#97]
In the RxTrax receipt there are a few minor differences in the receipt from POS Receipt. 
1.) Can we also Print on the tender type line the Health Card and Amount and then the Credit Card and amount separately? 
**Item 1 is still open**.

2.) Also the ~ for the healthcare amounts should print after the Extended price and Not before the item. 
**Item 2 - Added separately in #125** 

3.) Do we have to have the RX: and then our RX description printed. Please remove the prefix "RX:" 
**Item 3 is fixed.**

4.) We have what is called the footer of the receipt that our customers put in POS to print out a customer footer to the receipt between the Amount paid and the type of card used. 
**Item 4 - Added separately in #120** 

5.) Also, please maintain the order if the items on the Receipt.
**Item 5 is fixed.**

![minor receipt issue](https://cloud.githubusercontent.com/assets/8714134/22318914/b8ec4f86-e354-11e6-8ada-3a8186dd07ac.jpg)
![pos receipt](https://cloud.githubusercontent.com/assets/8714134/22318915/b8f595aa-e354-11e6-89e8-e6b18f97a269.jpg)

**Comment by jjamminjim** [comment]
@brprashanth Could you please break this into separate issues? 2, 3, and 5 are fixed
