### ISSUE TITLE
(#130) Card Transaction Request - Please include it under the Transaction information

### ISSUE THREAD

**Issue by brprashanth** [rxtrax/tracking#98]
Please include the card transaction request object under the Transaction information.
This way, we will be easily able to debug, troubleshoot issues

**Comment by jjamminjim** [comment]
@brprashanth : All of this information is available through TransactionLogs items. If these are not available to you then perhaps the api team can make sure they are returned to you with Transactions and you can save them in your DB. @jasonmadrid?

**Comment by jjamminjim** [comment]
Returned under the `request` field
